Repository Automattic/simplenote-android, pull requests merged in 2019-06, with the labels that each got.

#644 Use Status Bar Height as Padding Instead of Static Value
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/res/layout/activity_notes.xml
  Simplenote/src/main/res/values-v21/dimens.xml
  Simplenote/src/main/res/values/dimens.xml
Labels: bug, good first issue

#693 Update GitHub Documentation
  README.md
  RELEASE-NOTES.txt
Labels: task

#691 Update Gradle Plugin
  .travis.yml
  Simplenote/build.gradle
  Wear/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: [status] needs code review, task, tooling

#694 Add API Suppression
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: [status] needs code review, task

#692 Update Color Resources
  Simplenote/src/androidTest/java/com/automattic/simplenote/utils/ChecklistsTest.java
  Simplenote/src/main/java/com/automattic/simplenote/AboutActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/SnackbarUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/widgets/SimplenoteEditText.java
  Simplenote/src/main/res/drawable-v21/list_background_simplestyle_dark.xml
  Simplenote/src/main/res/drawable/list_background_simplestyle_dark.xml
  Simplenote/src/main/res/drawable/list_divider.xml
  Simplenote/src/main/res/drawable/list_divider_dark.xml
  Simplenote/src/main/res/drawable/pin_icon.xml
  Simplenote/src/main/res/drawable/pin_icon_dark.xml
  Simplenote/src/main/res/drawable/pin_icon_pinned.xml
  Simplenote/src/main/res/drawable/pin_icon_pinned_dark.xml
  Simplenote/src/main/res/drawable/pinned_note_widget_background.xml
  Simplenote/src/main/res/drawable/tag_bg.xml
  Simplenote/src/main/res/drawable/tag_bg_dark.xml
  Simplenote/src/main/res/layout-v21/bottom_sheet_history.xml
  Simplenote/src/main/res/layout/auth_preference.xml
  Simplenote/src/main/res/layout/bottom_sheet_history.xml
  Simplenote/src/main/res/layout/bottom_sheet_info.xml
  Simplenote/src/main/res/layout/bottom_sheet_share.xml
  Simplenote/src/main/res/layout/fragment_about.xml
  Simplenote/src/main/res/layout/fragment_tags_list.xml
  Simplenote/src/main/res/layout/pinned_note_widget.xml
  Simplenote/src/main/res/layout/sign_in_footer.xml
  Simplenote/src/main/res/values-night/styles_simplestyle.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/styles_simplestyle.xml
Labels: [status] needs code review, task

#700 Update Integer Division
  Simplenote/src/main/java/com/automattic/simplenote/models/Note.java
Labels: task

#699 Add Button Hint
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
Labels: task

#698 Remove Welcome Button
  Simplenote/src/main/res/drawable/welcome_button.xml
  Simplenote/src/main/res/drawable/welcome_button_selected.xml
  Simplenote/src/main/res/drawable/welcome_button_selector.xml
  Simplenote/src/main/res/values/colors.xml
Labels: task

#686 Update Note Widget
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidget.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetConfigureActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PinnedNoteWidget.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/analytics/AnalyticsTracker.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/PrefUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/WidgetUtils.java
  Simplenote/src/main/res/drawable-nodpi/note_widget_preview.png
  Simplenote/src/main/res/drawable-nodpi/pinned_note_preview.png
  Simplenote/src/main/res/drawable/note_widget_background.xml
  Simplenote/src/main/res/drawable/pinned_note_widget_background.xml
  Simplenote/src/main/res/layout-v23/note_widget.xml
  Simplenote/src/main/res/layout/fragment_notes_list.xml
  Simplenote/src/main/res/layout/note_widget.xml
  Simplenote/src/main/res/layout/note_widget_configure.xml
  Simplenote/src/main/res/layout/note_widget_configure_list.xml
  Simplenote/src/main/res/layout/pinned_note_widget.xml
  Simplenote/src/main/res/layout/pinned_note_widget_configure.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-v14/dimens.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles_simplestyle.xml
  Simplenote/src/main/res/xml/note_widget_info.xml
  Simplenote/src/main/res/xml/pinned_note_widget_info.xml
Labels: [status] needs code review, [status] needs design review, enhancement

#697 Fix accessibility warnings
  Simplenote/src/main/java/com/automattic/simplenote/widgets/NoteEditorViewPager.java
  Simplenote/src/main/res/layout/nav_drawer_footer.xml
  Simplenote/src/main/res/layout/nav_drawer_row.xml
Labels: accessibility, task

#704 Add Hide Keyboard
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DisplayUtils.java
Labels: [status] needs code review, task

#695 Update Status Bar
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/res/values-night-v21/styles.xml
  Simplenote/src/main/res/values-night/styles_simplestyle.xml
  Simplenote/src/main/res/values-v21/styles.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/styles_simplestyle.xml
Labels: task

#701 Update Touch Feedback
  Simplenote/src/main/res/drawable/selectable_background_simplestyle.xml
  Simplenote/src/main/res/layout/activity_note_editor.xml
  Simplenote/src/main/res/layout/dialog_wordpress_post.xml
  Simplenote/src/main/res/layout/fragment_notes_list.xml
  Simplenote/src/main/res/layout/nav_drawer_footer.xml
  Simplenote/src/main/res/layout/sign_in_footer.xml
  Simplenote/src/main/res/values-night/styles_simplestyle.xml
  Simplenote/src/main/res/values/styles_simplestyle.xml
Labels: [status] needs code review, [status] needs design review, task

#703 Remove Share Selector
  Simplenote/src/main/res/drawable/ic_collaborate_selector.xml
  Simplenote/src/main/res/drawable/ic_publish_selector.xml
  Simplenote/src/main/res/drawable/ic_unpublish_selector.xml
  Simplenote/src/main/res/drawable/ic_wordpress_post_selector.xml
  Simplenote/src/main/res/layout/bottom_sheet_share.xml
Labels: task

#713 Fix release notes for 1.8.0
  RELEASE-NOTES.txt
Labels: tooling
