Repository Automattic/simplenote-android, pull requests merged in 2019-09, with the labels that each got.

#798 Merge Release/2.0 into develop
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
Labels: release

#799 Update About Style
  Simplenote/src/main/java/com/automattic/simplenote/AboutActivity.java
  Simplenote/src/main/res/layout/activity_about.xml
  Simplenote/src/main/res/values/styles.xml
Labels: [status] needs code review, debt

#791 Update Note List
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetConfigureActivity.java
  Simplenote/src/main/res/drawable/ic_add_24dp.xml
  Simplenote/src/main/res/drawable/ic_feed_24dp.xml
  Simplenote/src/main/res/layout/fragment_about.xml
  Simplenote/src/main/res/layout/fragment_note_editor.xml
  Simplenote/src/main/res/layout/fragment_notes_list.xml
  Simplenote/src/main/res/layout/fragment_tags_list.xml
  Simplenote/src/main/res/layout/list_item_single_choice.xml
  Simplenote/src/main/res/layout/note_list_row.xml
  Simplenote/src/main/res/layout/note_widget.xml
  Simplenote/src/main/res/layout/note_widget_configure_list.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/styles.xml
Labels: enhancement

#802 Crash Save Note
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
Labels: [status] needs code review, bug, crash

#792 Update Navigation Bar
  Simplenote/src/main/java/com/automattic/simplenote/BottomSheetDialogBase.java
  Simplenote/src/main/java/com/automattic/simplenote/HistoryBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/InfoBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/ShareBottomSheetDialog.java
  Simplenote/src/main/res/layout/bottom_sheet_info.xml
  Simplenote/src/main/res/values-night-v27/styles.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values-v27/styles.xml
  Simplenote/src/main/res/values/styles.xml
Labels: enhancement

#800 Tags List Empty
  Simplenote/src/main/java/com/automattic/simplenote/TagsListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/widgets/EmptyViewRecyclerView.java
  Simplenote/src/main/res/layout/fragment_notes_list.xml
  Simplenote/src/main/res/layout/fragment_tags_list.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/styles.xml
Labels: bug

#804 Merge Release/2.0 into develop
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
Labels: release

#803 Open Preview Tablet
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: enhancement

#805 Update About Status
  Simplenote/src/main/res/values-v27/styles.xml
Labels: enhancement

#810 Provide installable APK for every Pull Request
  .circleci/config.yml
  .configure
  .configure-files/automattic.jks.enc
  .configure-files/gradle.properties.enc
  .configure-files/sentry.properties.enc
  .gitignore
  Gemfile.lock
  Simplenote/build.gradle
  fastlane/Pluginfile
Labels: tooling

#806 Update Note Editor
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/TagsMultiAutoCompleteTextView.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ThemeUtils.java
  Simplenote/src/main/res/layout-large-land/fragment_note_editor.xml
  Simplenote/src/main/res/layout/fragment_note_editor.xml
  Simplenote/src/main/res/layout/tag_autocomplete_list_item.xml
  Simplenote/src/main/res/layout/tags_textview.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/attrs.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/styles.xml
Labels: enhancement

#812 Note List Padding
  Simplenote/src/main/res/layout/fragment_notes_list.xml
Labels: task

#811 Update Color 2.2.0
  Simplenote/src/main/res/values/colors.xml
Labels: task

#815 Rename Title Resource
  Simplenote/src/main/res/layout/note_list_row.xml
  Simplenote/src/main/res/layout/note_widget.xml
  Simplenote/src/main/res/layout/tag_autocomplete_list_item.xml
  Simplenote/src/main/res/values/dimens.xml
Labels: [status] needs code review, bug

#813 Add Center Credentials
  Simplenote/build.gradle
Labels: enhancement
