Repository Automattic/simplenote-android, pull requests merged in 2019-11, with the labels that each got.

#867 Merge Release/2.2 into develop
  Simplenote/build.gradle
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-cy/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/86.txt
  fastlane/metadata/android/ar/changelogs/88.txt
  fastlane/metadata/android/de-DE/changelogs/86.txt
  fastlane/metadata/android/de-DE/changelogs/88.txt
  fastlane/metadata/android/es-ES/changelogs/86.txt
  fastlane/metadata/android/es-ES/changelogs/88.txt
  fastlane/metadata/android/fr-FR/changelogs/86.txt
  fastlane/metadata/android/fr-FR/changelogs/88.txt
  fastlane/metadata/android/id/changelogs/86.txt
  fastlane/metadata/android/id/changelogs/88.txt
  fastlane/metadata/android/it-IT/changelogs/86.txt
  fastlane/metadata/android/it-IT/changelogs/88.txt
  fastlane/metadata/android/iw-IL/changelogs/86.txt
  fastlane/metadata/android/iw-IL/changelogs/88.txt
  fastlane/metadata/android/ja-JP/changelogs/86.txt
  fastlane/metadata/android/ja-JP/changelogs/88.txt
  fastlane/metadata/android/ko-KR/changelogs/86.txt
  fastlane/metadata/android/ko-KR/changelogs/88.txt
  fastlane/metadata/android/nl-NL/changelogs/86.txt
  fastlane/metadata/android/nl-NL/changelogs/88.txt
  fastlane/metadata/android/pt-BR/changelogs/86.txt
  fastlane/metadata/android/pt-BR/changelogs/88.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/86.txt
  fastlane/metadata/android/ru-RU/changelogs/88.txt
  fastlane/metadata/android/sv-SE/changelogs/86.txt
  fastlane/metadata/android/sv-SE/changelogs/88.txt
  fastlane/metadata/android/tr-TR/changelogs/86.txt
  fastlane/metadata/android/tr-TR/changelogs/88.txt
  fastlane/metadata/android/zh-CN/changelogs/86.txt
  fastlane/metadata/android/zh-CN/changelogs/88.txt
  fastlane/metadata/android/zh-TW/changelogs/86.txt
  fastlane/metadata/android/zh-TW/changelogs/88.txt
Labels: release

#868 Update shield for 2.2
  README.md
Labels: release

#865 Issue/843 add autocomplete suggestions
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/models/Suggestion.java
  Simplenote/src/main/res/layout/fragment_notes_list.xml
  Simplenote/src/main/res/layout/search_suggestion.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/strings.xml
Labels: enhancement

#875 Update Preference Manager
  Simplenote/src/main/java/com/automattic/simplenote/InfoBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/analytics/AnalyticsTrackerNosara.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/PrefUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ThemeUtils.java
Labels: [status] needs code review, debt

#874 Update Background Shades
  Simplenote/src/main/assets/dark.css
  Simplenote/src/main/res/values/colors.xml
Labels: task

#876 Update Search Padding
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: task

#880 Issue/879 note sync pause
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
Labels: [status] needs code review, bug

#877 Update Empty Views
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsListFragment.java
  Simplenote/src/main/res/layout-large-land/fragment_note_editor.xml
  Simplenote/src/main/res/layout/empty_view.xml
  Simplenote/src/main/res/layout/fragment_note_editor.xml
  Simplenote/src/main/res/layout/fragment_notes_list.xml
  Simplenote/src/main/res/layout/fragment_tags_list.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/attrs.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
Labels: [status] needs code review, enhancement

#882 Stop Splitting Surrogates
  Simplenote/build.gradle
Labels: bug

#870 Issue/844 add recent suggestions
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/Simplenote.java
  Simplenote/src/main/java/com/automattic/simplenote/models/Preferences.java
  Simplenote/src/main/res/layout/search_suggestion.xml
  Simplenote/src/main/res/values/strings.xml
Labels: enhancement

#871 Support the unicode bullet as a list item bullet in unordered lists
  Simplenote/src/main/java/com/automattic/simplenote/utils/AutoBullet.java
Labels: enhancement

#883 Issue/881 remove relevance sorting
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/res/drawable/ic_arrow_up_16dp.xml
  Simplenote/src/main/res/layout/search_sort.xml
  Simplenote/src/main/res/menu/search_sort.xml
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, [status] needs design review, enhancement

#886 Crash Resume Filter
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: [status] needs code review, crash

#889 Debt/remove static async task warnings
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsListFragment.java
Labels: [status] needs code review, debt

#887 Update Passcode Layout
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/src/main/res/drawable/ic_backspace_24dp.xml
  Simplenote/src/main/res/drawable/ic_fingerprint_24dp.xml
  Simplenote/src/main/res/drawable/ic_fingerprint_48dp.xml
  Simplenote/src/main/res/layout-sw600dp/app_passcode_keyboard.xml
  Simplenote/src/main/res/layout/app_passcode_keyboard.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/drawables.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
Labels: [status] needs code review, enhancement

#894 Issue/893 add global search
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
Labels: [status] needs code review, enhancement

#895 Navigation Locked Search
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: [status] needs code review, bug

#897 Update Signin Login
  README.md
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidget.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetConfigureActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/SimplenoteAuthenticationActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/WordPressDialogFragment.java
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, debt
