Repository Automattic/simplenote-android, pull requests merged in 2019-10, with the labels that each got.

#820 App Bar Title
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/widgets/TypefaceSpan.java
Labels: enhancement

#801 Update Selected Color
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/styles.xml
Labels: enhancement

#819 Update Dark Background
  RELEASE-NOTES.txt
  Simplenote/src/main/assets/dark.css
  Simplenote/src/main/res/layout/activity_notes.xml
  Simplenote/src/main/res/values-night-v27/styles.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values-v27/styles.xml
  Simplenote/src/main/res/values/attrs.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/styles.xml
Labels: [status] needs design review, enhancement

#825 Remove Location Permission
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, debt

#824 Remove Category Key
  Simplenote/src/main/res/xml/preferences.xml
Labels: debt

#823 Update Pinned Icon
  Simplenote/src/main/res/drawable/ic_pinned_16dp.xml
  Simplenote/src/main/res/drawable/ic_pinned_24dp.xml
  Simplenote/src/main/res/layout/note_list_row.xml
  Simplenote/src/main/res/menu/bulk_edit.xml
Labels: enhancement

#821 Update Default Theme
  Simplenote/src/main/java/com/automattic/simplenote/utils/ThemeUtils.java
Labels: task

#827 Update Merge Conflicts
  Simplenote/src/main/assets/dark.css
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/res/color/bg_drawer_selector_dark.xml
  Simplenote/src/main/res/color/bg_drawer_selector_light.xml
  Simplenote/src/main/res/drawable/bg_list_popup.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/styles.xml
Labels: bug

#816 Update Edit Tags
  Simplenote/src/main/java/com/automattic/simplenote/TagsListFragment.java
  Simplenote/src/main/res/layout/tags_list_row.xml
  Simplenote/src/main/res/values/dimens.xml
Labels: enhancement

#822 Update Dark Accent
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/WordPressDialogFragment.java
  Simplenote/src/main/res/layout/activity_note_editor.xml
  Simplenote/src/main/res/values/styles.xml
Labels: enhancement

#829 Fix typo in Fastfile
  fastlane/Fastfile
Labels: tooling

#830 Merge Release/2.1 into Develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
Labels: release

#834 Update Markdown Action
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: [status] needs code review, bug

#832 Issue/828 update note tags
  Simplenote/src/main/res/values-night/styles.xml
Labels: [status] needs code review, task

#833 Update Color Shades
  Simplenote/src/main/res/values/colors.xml
Labels: [status] needs code review, task

#835 Update Visibility Icon
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: release

#845 Update Gradle Dependencies
  .circleci/config.yml
  .gitignore
  .travis.yml
  Simplenote/build.gradle
  Wear/build.gradle
Labels: [status] needs code review, tooling

#846 Remove Escape String
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
Labels: [status] needs code review, bug, i18n

#848 Merge Release/2.1 into Master
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/TagsListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/BaseCursorAdapter.java
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/82.txt
  fastlane/metadata/android/ar/changelogs/86.txt
  fastlane/metadata/android/de-DE/changelogs/82.txt
  fastlane/metadata/android/de-DE/changelogs/86.txt
  fastlane/metadata/android/es-ES/changelogs/82.txt
  fastlane/metadata/android/es-ES/changelogs/86.txt
  fastlane/metadata/android/fr-FR/changelogs/82.txt
  fastlane/metadata/android/fr-FR/changelogs/86.txt
  fastlane/metadata/android/id/changelogs/82.txt
  fastlane/metadata/android/id/changelogs/86.txt
  fastlane/metadata/android/it-IT/changelogs/82.txt
  fastlane/metadata/android/it-IT/changelogs/86.txt
  fastlane/metadata/android/iw-IL/changelogs/82.txt
  fastlane/metadata/android/iw-IL/changelogs/86.txt
  fastlane/metadata/android/ja-JP/changelogs/82.txt
  fastlane/metadata/android/ja-JP/changelogs/86.txt
  fastlane/metadata/android/ko-KR/changelogs/82.txt
  fastlane/metadata/android/ko-KR/changelogs/86.txt
  fastlane/metadata/android/nl-NL/changelogs/82.txt
  fastlane/metadata/android/nl-NL/changelogs/86.txt
  fastlane/metadata/android/pt-BR/changelogs/82.txt
  fastlane/metadata/android/pt-BR/changelogs/86.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/82.txt
  fastlane/metadata/android/ru-RU/changelogs/86.txt
  fastlane/metadata/android/sv-SE/changelogs/82.txt
  fastlane/metadata/android/sv-SE/changelogs/86.txt
  fastlane/metadata/android/tr-TR/changelogs/82.txt
  fastlane/metadata/android/tr-TR/changelogs/86.txt
  fastlane/metadata/android/zh-CN/changelogs/82.txt
  fastlane/metadata/android/zh-CN/changelogs/86.txt
  fastlane/metadata/android/zh-TW/changelogs/82.txt
  fastlane/metadata/android/zh-TW/changelogs/86.txt
  tools/update-translations.sh
Labels: release

#850 Update README.md
  README.md
Labels: release

#851 Update fastlane
  .ruby-version
  Gemfile
  Gemfile.lock
Labels: tooling

#856 Merge Release/2.2 into develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
Labels: release

#855 Update Tablet Divider
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/res/drawable-hdpi/right_shadow.9.png
  Simplenote/src/main/res/layout/fragment_notes_list.xml
Labels: task

#852 Issue/840 update search view
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/res/layout/activity_note_editor.xml
  Simplenote/src/main/res/layout/toolbar.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/styles.xml
Labels: enhancement

#863 Issue/862 navigation unlocked search
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: bug

#853 Issue/841 update search list
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DateTimeUtils.java
  Simplenote/src/main/res/layout/note_list_row.xml
Labels: enhancement
