Repository Automattic/simplenote-android, pull requests merged in 2019-08, with the labels that each got.

#763 Issue/720 update material components
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/res/layout/bottom_sheet_history.xml
  Simplenote/src/main/res/layout/dialog_wordpress_post.xml
  Simplenote/src/main/res/layout/fragment_notes_list.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/styles.xml
Labels: [status] needs code review, task

#767 Issue/758 widget list order
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetConfigureActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/PrefUtils.java
Labels: [status] needs code review, task

#766 Issue/757 note widget resizable
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidget.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetConfigureActivity.java
  Simplenote/src/main/res/layout-v23/note_widget.xml
  Simplenote/src/main/res/layout/note_widget.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/xml/note_widget_info.xml
Labels: [status] needs code review, task

#765 Issue/722 update theme transition
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ThemeUtils.java
Labels: [status] needs code review, task

#771 Update Login Signup
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/SignInActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/SimplenoteAuthenticationActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/SimplenoteCredentialsActivity.java
  Simplenote/src/main/res/drawable/ic_wordpress_24dp.xml
  Simplenote/src/main/res/layout-sw600dp/app_passcode_keyboard.xml
  Simplenote/src/main/res/layout/sign_in_footer.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/drawables.xml
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, [status] needs design review, enhancement

#773 Issue/772 navigation drawer unlocked
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: [status] needs code review, bug

#778 Update release-toolkit to 0.7.1
  Gemfile.lock
  fastlane/Pluginfile
Labels: tooling

#779 Update Tab Background
  Simplenote/src/main/res/layout/activity_note_editor.xml
Labels: [status] needs code review, task

#781 PR Template: Update Release section to be required
  .github/PULL_REQUEST_TEMPLATE.md
Labels: tooling

#777 Update Password Length
  Simplenote/build.gradle
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, enhancement

#782 Merge Release/2.0 into develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
Labels: release

#784 Add beta build lane
  fastlane/Fastfile
Labels: tooling

#789 Merge Release/2.0 into develop
  fastlane/Fastfile
Labels: release

#790 Update About Status
  Simplenote/src/main/res/values/styles.xml
Labels: [status] needs code review, bug

#730 Implement RecyclerView for tags list
  Simplenote/src/main/java/com/automattic/simplenote/TagsListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/BaseCursorAdapter.java
  Simplenote/src/main/res/layout/fragment_tags_list.xml
  Simplenote/src/main/res/layout/tags_list_row.xml
Labels: debt

#788 Note Saving Preview
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
Labels: [status] needs code review, bug

#794 Remove Creator Comments
  Simplenote/src/main/java/com/automattic/simplenote/AboutActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/AboutFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/BottomSheetDialogBase.java
  Simplenote/src/main/java/com/automattic/simplenote/HistoryBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/InfoBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/ShareBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/models/NoteCountIndexer.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DateTimeUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DrawableUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/NoteUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ShareButtonAdapter.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/SimplenoteLinkify.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/SnackbarUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/TagsAdapter.java
  Simplenote/src/main/java/com/automattic/simplenote/widgets/TypefaceSpan.java
Labels: [status] needs code review, debt

#795 Hard Coded Colors
  Simplenote/src/main/java/com/automattic/simplenote/WordPressDialogFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ChecklistUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/widgets/SimplenoteEditText.java
  Simplenote/src/main/res/drawable/ic_check_box_24px.xml
  Simplenote/src/main/res/drawable/ic_check_box_outline_blank_24px.xml
  Simplenote/src/main/res/drawable/ic_checkbox_checked_24px.xml
  Simplenote/src/main/res/drawable/ic_checkbox_unchecked_24px.xml
  Simplenote/src/main/res/drawable/ic_collaborate_48dp.xml
  Simplenote/src/main/res/drawable/ic_publish_48dp.xml
  Simplenote/src/main/res/drawable/ic_shortcut_create_48dp.xml
  Simplenote/src/main/res/drawable/ic_unpublish_48dp.xml
  Simplenote/src/main/res/drawable/ic_wordpress_post_48dp.xml
Labels: debt

#796 Update Snackbar Background
  Simplenote/src/main/java/com/automattic/simplenote/utils/SnackbarUtils.java
Labels: enhancement
