Repository Automattic/simplenote-android, pull requests merged in 2019-12, with the labels that each got.

#898 Update Welcome Note
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, enhancement

#900 Merge Release/2.3 into develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
Labels: release

#901 Merge Release/2.3 into Master
  README.md
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  Simplenote/src/main/assets/dark.css
  Simplenote/src/main/java/com/automattic/simplenote/InfoBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidget.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetConfigureActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/Simplenote.java
  Simplenote/src/main/java/com/automattic/simplenote/SimplenoteAuthenticationActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/WordPressDialogFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/analytics/AnalyticsTrackerNosara.java
  Simplenote/src/main/java/com/automattic/simplenote/models/Preferences.java
  Simplenote/src/main/java/com/automattic/simplenote/models/Suggestion.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/AutoBullet.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DateTimeUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/PrefUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ThemeUtils.java
  Simplenote/src/main/res/drawable-hdpi/right_shadow.9.png
  Simplenote/src/main/res/drawable/ic_arrow_down_16dp.xml
  Simplenote/src/main/res/drawable/ic_arrow_up_16dp.xml
  Simplenote/src/main/res/drawable/ic_backspace_24dp.xml
  Simplenote/src/main/res/drawable/ic_fingerprint_24dp.xml
  Simplenote/src/main/res/drawable/ic_fingerprint_48dp.xml
  Simplenote/src/main/res/drawable/ic_sort_order_24dp.xml
  Simplenote/src/main/res/layout-large-land/fragment_note_editor.xml
  Simplenote/src/main/res/layout-sw600dp/app_passcode_keyboard.xml
  Simplenote/src/main/res/layout/activity_note_editor.xml
  Simplenote/src/main/res/layout/app_passcode_keyboard.xml
  Simplenote/src/main/res/layout/empty_view.xml
  Simplenote/src/main/res/layout/fragment_note_editor.xml
  Simplenote/src/main/res/layout/fragment_notes_list.xml
  Simplenote/src/main/res/layout/fragment_tags_list.xml
  Simplenote/src/main/res/layout/note_list_row.xml
  Simplenote/src/main/res/layout/search_sort.xml
  Simplenote/src/main/res/layout/search_suggestion.xml
  Simplenote/src/main/res/layout/toolbar.xml
  Simplenote/src/main/res/menu/search_sort.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/attrs.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/drawables.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
Labels: release

#903 Update Tablet Selection
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: [status] needs code review, bug, crash

#904 Update Link Actions
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/res/drawable/ic_browser_24dp.xml
  Simplenote/src/main/res/menu/view_link.xml
Labels: bug

#905 Merge Release/2.3 into develop
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: release

#908 Update Date Format
  Simplenote/src/main/java/com/automattic/simplenote/HistoryBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/InfoBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DateTimeUtils.java
Labels: [status] needs code review, enhancement

#909 Merge 2.3-rc-3 into develop
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/HistoryBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/InfoBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DateTimeUtils.java
Labels: release

#910 Crash Date Pattern
  Simplenote/src/main/java/com/automattic/simplenote/utils/DateTimeUtils.java
Labels: bug, crash

#912 Queued Local Deletion
  RELEASE-NOTES.txt
  Simplenote/build.gradle
Labels: [status] needs code review, bug

#915 Add Tags Scrollbar
  Simplenote/src/main/res/layout/fragment_tags_list.xml
Labels: [status] needs code review, enhancement

#916 Update Async Tasks
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsListFragment.java
  Wear/src/main/java/com/automattic/simplenote/CreateNoteActivity.java
Labels: [status] needs code review, debt
