Repository Automattic/simplenote-android, pull requests merged in 2019-05, with the labels that each got.

#646 Use Unicode No-Break Space to Prevent Checklist Span Break
  Simplenote/src/main/java/com/automattic/simplenote/utils/ChecklistUtils.java
Labels: [status] needs code review, bug

#673 Update GitHub Templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/---bug-report.md
  .github/ISSUE_TEMPLATE/---feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: tooling

#667 Issue/add adaptive icon
  Simplenote/src/debug/res/drawable/ic_launcher_foreground.xml
  Simplenote/src/debug/res/mipmap-hdpi/ic_launcher.png
  Simplenote/src/debug/res/mipmap-mdpi/ic_launcher.png
  Simplenote/src/debug/res/mipmap-xhdpi/ic_launcher.png
  Simplenote/src/debug/res/mipmap-xxhdpi/ic_launcher.png
  Simplenote/src/debug/res/mipmap-xxxhdpi/ic_launcher.png
  Simplenote/src/main/res/drawable/ic_launcher_background.xml
  Simplenote/src/main/res/drawable/ic_launcher_foreground.xml
  Simplenote/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  metadata/ic_launcher.svg
  metadata/ic_launcher_web.png
Labels: [status] needs code review

#670 Issue/ignore gradle properties
  .gitignore
  .travis.yml
  README.md
  Simplenote/gradle.properties
  Simplenote/gradle.properties-example
Labels: [status] needs code review

#676 Issue/update dependency tracks
  Simplenote/build.gradle
Labels: analytics

#627 Note Shortcut Widget
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/PinnedNoteWidget.java
  Simplenote/src/main/java/com/automattic/simplenote/PinnedNoteWidgetConfigureActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/PrefUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/WidgetUtils.java
  Simplenote/src/main/res/drawable-nodpi/pinned_note_preview.png
  Simplenote/src/main/res/drawable/pinned_note_widget_background.xml
  Simplenote/src/main/res/layout/pinned_note_widget.xml
  Simplenote/src/main/res/layout/pinned_note_widget_configure.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-v14/dimens.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/xml/pinned_note_widget_info.xml
Labels: enhancement

#604 Sensitive content is now hidden from the recent apps when app lock is enabled
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DisplayUtils.java
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/xml/preferences.xml
Labels: enhancement

#572 Show keyboard after returning to a note
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
Labels: enhancement

#678 Issue/642 resize share icons
  Simplenote/src/main/java/com/automattic/simplenote/ShareBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/IconResizer.java
  Simplenote/src/main/res/drawable/ic_collaborate_48dp.xml
  Simplenote/src/main/res/drawable/ic_publish_48dp.xml
  Simplenote/src/main/res/drawable/ic_unpublish_48dp.xml
  Simplenote/src/main/res/drawable/ic_wordpress_post_48dp.xml
  Simplenote/src/main/res/values/dimens.xml
Labels: [status] needs code review, bug

#677 Issue/build gradle properties
  README.md
  Simplenote/build.gradle
Labels: tooling

#648 Fix Inspection Warnings
  Simplenote/src/main/java/com/automattic/simplenote/AboutFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/AutoBullet.java
  Simplenote/src/main/java/com/automattic/simplenote/widgets/TypefaceSpan.java
Labels: debt

#645 Checklist Cursor and Keyboard Adjustments
  Simplenote/src/main/java/com/automattic/simplenote/widgets/SimplenoteEditText.java
Labels: [status] needs code review, bug

#685 Add CircleCI Config
  .circleci/config.yml
Labels: tooling
