Repository Automattic/simplenote-android, pull requests merged in 2019-07, with the labels that each got.

#715 Merge release 1.8.0 into develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-cy/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  Simplenote/src/main/res/values/available_languages.xml
Labels: Releases

#711 Feature/add get prs list
  .bundle/config
  .gitignore
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
  fastlane/env.example
Labels: tooling

#716 Update Readme 1.8.0
  README.md
Labels: task

#712 Add translations for release notes and metadata
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/src/main/res/values/strings.xml
Labels: tooling

#724 Update Status Bar
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/res/values/styles.xml
Labels: task

#723 Issue/708 first tag focus
  Simplenote/src/main/res/layout/nav_drawer_row.xml
Labels: bug

#727 Update to targetSdkVersion 28
  .travis.yml
  Simplenote/build.gradle
  Simplenote/src/main/AndroidManifest.xml
  Wear/build.gradle
Labels: tooling

#729 Issue/728 update sign out
  Simplenote/src/main/res/layout/auth_preference.xml
  Simplenote/src/main/res/xml/preferences.xml
Labels: [status] needs code review, bug

#705 Update Passcode Layout
  Simplenote/build.gradle
  Simplenote/src/main/res/drawable/ic_backspace_white_36dp.xml
  Simplenote/src/main/res/drawable/ic_fingerprint_48dp.xml
  Simplenote/src/main/res/drawable/ic_simplenote_24dp.xml
  Simplenote/src/main/res/layout-sw600dp/app_passcode_keyboard.xml
  Simplenote/src/main/res/layout/app_passcode_keyboard.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
Labels: task

#733 Issue/732 crash bullet list
  Simplenote/src/main/java/com/automattic/simplenote/utils/AutoBullet.java
Labels: bug, crash

#734 Issue/731 remove simperium link
  Simplenote/src/main/java/com/automattic/simplenote/AboutFragment.java
  Simplenote/src/main/res/layout/fragment_about.xml
  Simplenote/src/main/res/values/strings.xml
Labels: enhancement

#737 Merge release 1.8.1 into develop
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/utils/AutoBullet.java
  Simplenote/src/main/res/layout/nav_drawer_row.xml
Labels: release

#738 Add Sentry (and the secret store)
  .configure
  .gitignore
  Gemfile.lock
  Simplenote/build.gradle
  Simplenote/gradle.properties-example
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/Simplenote.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/CrashUtils.java
  Wear/build.gradle
  fastlane/Pluginfile
Labels: analytics, tooling

#707 Full screen note editing on tablets while on landscape orientation
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/res/drawable/ic_sidebar_24dp.xml
  Simplenote/src/main/res/layout/activity_notes.xml
  Simplenote/src/main/res/menu/notes_list.xml
  Simplenote/src/main/res/values/strings.xml
Labels: enhancement

#740 Bugfix: Correct "Restore note" icon is now being shown in markdown preview of deleted notes
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
Labels: bug

#735 Fix Correctness>Messages warnings
  Simplenote/src/main/res/values-iw/strings.xml
Labels: task

#742 Add tagged version of sentry
  Simplenote/build.gradle
Labels: analytics, debt

#743 Fix bundle version and gitignore
  .gitignore
  Gemfile.lock
Labels: tooling

#744 Change versioning in build.gradle
  Simplenote/build.gradle
Labels: tooling

#714 Note counts for tags with uppercase letters are now shown correctly
  Simplenote/src/main/java/com/automattic/simplenote/TagsListFragment.java
Labels: bug

#747 Update Keyboard Super
  Simplenote/src/main/java/com/automattic/simplenote/widgets/SimplenoteEditText.java
Labels: [status] needs code review, bug

#752 Merge release 1.8.2 into develop
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/widgets/SimplenoteEditText.java
Labels: release

#751 Merge Release/1.8.2 into Master
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/widgets/SimplenoteEditText.java
Labels: release

#753 Update Readme 1.8.2
  README.md
Labels: [status] needs code review, task

#745 Add codefreeze lane
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: tooling

#759 Update fastlane
  Gemfile
  Gemfile.lock
Labels: tooling
