Repository Automattic/simplenote-android, pull requests merged in 2020-11, with the labels that each got.

#1189 Merge release 2.3 RC 1 into develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
Labels: Releases

#1185 Add Styled Widgets (Part 2)
  Simplenote/src/main/java/com/automattic/simplenote/NoteListWidgetDark.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListWidgetFactory.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListWidgetLight.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetDarkConfigureActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetLightConfigureActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/PrefUtils.java
  Simplenote/src/main/res/drawable/bg_list_default.xml
  Simplenote/src/main/res/drawable/bg_list_mono.xml
  Simplenote/src/main/res/drawable/bg_ripple_oval_black.xml
  Simplenote/src/main/res/drawable/bg_ripple_oval_classic_dark.xml
  Simplenote/src/main/res/drawable/bg_ripple_oval_classic_light.xml
  Simplenote/src/main/res/drawable/bg_ripple_oval_default_dark.xml
  Simplenote/src/main/res/drawable/bg_ripple_oval_default_light.xml
  Simplenote/src/main/res/drawable/bg_ripple_oval_matrix_dark.xml
  Simplenote/src/main/res/drawable/bg_ripple_oval_matrix_light.xml
  Simplenote/src/main/res/drawable/bg_ripple_oval_mono_dark.xml
  Simplenote/src/main/res/drawable/bg_ripple_oval_mono_light.xml
  Simplenote/src/main/res/drawable/bg_ripple_oval_publication_dark.xml
  Simplenote/src/main/res/drawable/bg_ripple_oval_publication_light.xml
  Simplenote/src/main/res/drawable/bg_ripple_oval_sepia_dark.xml
  Simplenote/src/main/res/drawable/bg_ripple_oval_sepia_light.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_black.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_classic.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_default.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_matrix.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_mono.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_publication.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_sepia.xml
  Simplenote/src/main/res/layout/note_list_widget_item_dark_monospace.xml
  Simplenote/src/main/res/layout/note_list_widget_item_dark_serif.xml
  Simplenote/src/main/res/layout/note_list_widget_item_light_monospace.xml
  Simplenote/src/main/res/layout/note_list_widget_item_light_serif.xml
  Simplenote/src/main/res/layout/note_list_widget_light_black.xml
  Simplenote/src/main/res/layout/note_list_widget_light_classic.xml
  Simplenote/src/main/res/layout/note_list_widget_light_default.xml
  Simplenote/src/main/res/layout/note_list_widget_light_matrix.xml
  Simplenote/src/main/res/layout/note_list_widget_light_mono.xml
  Simplenote/src/main/res/layout/note_list_widget_light_publication.xml
  Simplenote/src/main/res/layout/note_list_widget_light_sepia.xml
  Simplenote/src/main/res/xml/note_list_widget_info_dark.xml
  Simplenote/src/main/res/xml/note_list_widget_info_light.xml
Labels: Part of a WIP Feature

#1192 Update Tag Canonical
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/TagUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/TagsMultiAutoCompleteTextView.java
Labels: task

#1195 Remove Large Dimensions
  Simplenote/src/main/res/values-large-xxxhdpi/dimens.xml
  Simplenote/src/main/res/values-xlarge-xxxhdpi/arrays.xml
  Simplenote/src/main/res/values-xlarge-xxxhdpi/integers.xml
Labels: [status] needs code review, task

#1198 Issue/1197 update dialog background
  Simplenote/src/main/res/values-night/styles.xml
Labels: Part of a WIP Feature, [status] needs code review

#1194 Update Checkbox Metrics
  Simplenote/src/androidTest/java/com/automattic/simplenote/utils/ChecklistsTest.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetDarkConfigureActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetLightConfigureActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ChecklistUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DisplayUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/SearchSnippetFormatter.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ThemeUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/widgets/SimplenoteEditText.java
  Simplenote/src/main/res/drawable/ic_checkbox_editor_checked_24dp.xml
  Simplenote/src/main/res/drawable/ic_checkbox_editor_unchecked_24dp.xml
  Simplenote/src/main/res/drawable/ic_checkbox_list_checked_24dp.xml
  Simplenote/src/main/res/drawable/ic_checkbox_list_unchecked_24dp.xml
  Simplenote/src/main/res/values/integers.xml
Labels: [status] needs code review, task

#1203 Update Style Recreate
  Simplenote/src/main/java/com/automattic/simplenote/StyleActivity.java
Labels: Part of a WIP Feature

#1201 Add Membership Setting
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/StyleActivity.java
  Simplenote/src/main/res/layout/preference_button.xml
  Simplenote/src/main/res/layout/preference_default.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/xml/preferences.xml
Labels: Part of a WIP Feature

#1200 Issue/1199 update untagged empty
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, task

#1207 Update Style Order
  Simplenote/src/main/java/com/automattic/simplenote/utils/ThemeUtils.java
Labels: Part of a WIP Feature, [status] needs code review, [status] needs design review

#1208 Update Welcome Note
  Simplenote/src/main/res/values/strings.xml
Labels: Part of a WIP Feature, [status] needs code review

#1210 Add Analytics Tracking
  Simplenote/src/main/java/com/automattic/simplenote/InfoBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/analytics/AnalyticsTracker.java
  Simplenote/src/main/java/com/automattic/simplenote/widgets/SimplenoteEditText.java
Labels: [status] needs code review, analytics

#1211 Merge Release/2.13 back into develop
  README.md
  Simplenote/build.gradle
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-cy/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/123.txt
  fastlane/metadata/android/ar/changelogs/125.txt
  fastlane/metadata/android/de-DE/changelogs/123.txt
  fastlane/metadata/android/de-DE/changelogs/125.txt
  fastlane/metadata/android/es-ES/changelogs/123.txt
  fastlane/metadata/android/es-ES/changelogs/125.txt
  fastlane/metadata/android/fr-FR/changelogs/123.txt
  fastlane/metadata/android/fr-FR/changelogs/125.txt
  fastlane/metadata/android/id/changelogs/123.txt
  fastlane/metadata/android/id/changelogs/125.txt
  fastlane/metadata/android/it-IT/changelogs/123.txt
  fastlane/metadata/android/it-IT/changelogs/125.txt
  fastlane/metadata/android/iw-IL/changelogs/123.txt
  fastlane/metadata/android/iw-IL/changelogs/125.txt
  fastlane/metadata/android/ja-JP/changelogs/123.txt
  fastlane/metadata/android/ja-JP/changelogs/125.txt
  fastlane/metadata/android/ko-KR/changelogs/123.txt
  fastlane/metadata/android/ko-KR/changelogs/125.txt
  fastlane/metadata/android/nl-NL/changelogs/123.txt
  fastlane/metadata/android/nl-NL/changelogs/125.txt
  fastlane/metadata/android/pt-BR/changelogs/123.txt
  fastlane/metadata/android/pt-BR/changelogs/125.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/123.txt
  fastlane/metadata/android/ru-RU/changelogs/125.txt
  fastlane/metadata/android/sv-SE/changelogs/123.txt
  fastlane/metadata/android/sv-SE/changelogs/125.txt
  fastlane/metadata/android/tr-TR/changelogs/123.txt
  fastlane/metadata/android/tr-TR/changelogs/125.txt
  fastlane/metadata/android/zh-CN/changelogs/123.txt
  fastlane/metadata/android/zh-CN/changelogs/125.txt
  fastlane/metadata/android/zh-TW/changelogs/123.txt
  fastlane/metadata/android/zh-TW/changelogs/125.txt
Labels: Releases

#1209 Update Lock Icon
  Simplenote/src/main/res/drawable/bg_style_locked.xml
  Simplenote/src/main/res/drawable/ic_lock_24dp.xml
  Simplenote/src/main/res/layout/style_list_row_black.xml
  Simplenote/src/main/res/layout/style_list_row_default.xml
  Simplenote/src/main/res/layout/style_list_row_matrix.xml
  Simplenote/src/main/res/layout/style_list_row_mono.xml
  Simplenote/src/main/res/layout/style_list_row_publication.xml
  Simplenote/src/main/res/layout/style_list_row_sepia.xml
  Simplenote/src/main/res/values-night/colors.xml
  Simplenote/src/main/res/values/colors.xml
Labels: Part of a WIP Feature, [status] needs code review

#1213 Merge Release/2.14 back into develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
Labels: Releases

#1214 Merge release notes for Release/2.14 into develop
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
Labels: Releases
