Repository Automattic/simplenote-android, pull requests merged in 2020-08, with the labels that each got.

#1114 Issue/1113 font resize swipe
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
Labels: [status] needs code review, bug

#1120 Disable installable builds temporarily
  .circleci/config.yml
Labels: Releases

#1104 Automatic upload to GooglePlay
  .configure
  .gitignore
  fastlane/Fastfile
Labels: tooling

#1117 Issue/1115 list widget condensed
  Simplenote/src/main/java/com/automattic/simplenote/NoteListWidgetFactory.java
Labels: [status] needs code review, enhancement

#1123 Issue/1029 publish network check
  Simplenote/src/main/java/com/automattic/simplenote/ShareBottomSheetDialog.java
Labels: enhancement

#1121 Add Style Setting (Part 2)
  Simplenote/src/main/assets/dark_black.css
  Simplenote/src/main/java/com/automattic/simplenote/StyleActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/PrefUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ThemeUtils.java
  Simplenote/src/main/res/drawable-night/bg_list_classic.xml
  Simplenote/src/main/res/drawable/bg_list_black.xml
  Simplenote/src/main/res/drawable/bg_list_classic.xml
  Simplenote/src/main/res/drawable/bg_list_default.xml
  Simplenote/src/main/res/drawable/bg_list_style_black.xml
  Simplenote/src/main/res/layout/style_list_row_black.xml
  Simplenote/src/main/res/layout/style_list_row_default.xml
  Simplenote/src/main/res/values-night-v27/styles.xml
  Simplenote/src/main/res/values-night/colors.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values-v27/styles.xml
  Simplenote/src/main/res/values/attrs.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
Labels: Part of a WIP Feature

#1124 Crash Right Click
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
Labels: [status] needs code review, crash

#1125 Add Style Setting (Part 3)
  Simplenote/src/main/assets/dark_sepia.css
  Simplenote/src/main/assets/light_sepia.css
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/StyleActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/PrefUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ThemeUtils.java
  Simplenote/src/main/res/drawable-night/bg_style_sepia.xml
  Simplenote/src/main/res/drawable/bg_list_sepia.xml
  Simplenote/src/main/res/drawable/bg_list_style_sepia.xml
  Simplenote/src/main/res/drawable/bg_style_sepia.xml
  Simplenote/src/main/res/layout/style_list_row_sepia.xml
  Simplenote/src/main/res/values-night/colors.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values-v27/styles.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
Labels: Part of a WIP Feature, [status] needs code review, [status] needs design review

#1126 Update Copy Clipboard
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/BrowserUtils.java
  Simplenote/src/main/res/values/strings.xml
Labels: bug

#1129 Use the `main` mobile secrets branch
  .configure
Labels: accessibility

#1127 Add Style Setting (Part 4)
  Simplenote/src/main/java/com/automattic/simplenote/StyleActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/PrefUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ThemeUtils.java
  Simplenote/src/main/res/drawable/bg_list_mono.xml
  Simplenote/src/main/res/layout/style_list_row_mono.xml
  Simplenote/src/main/res/values-night/colors.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
Labels: Part of a WIP Feature

#1128 Add App Log
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/AboutFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/InfoBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/Simplenote.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/AppLog.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DisplayUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/NetworkUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/NoteUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/PrefUtils.java
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/xml/preferences.xml
Labels: [status] needs code review, task

#1133 Add Style Setting (Part 5)
  Simplenote/src/main/java/com/automattic/simplenote/StyleActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/PrefUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ThemeUtils.java
  Simplenote/src/main/res/drawable/bg_list_publication.xml
  Simplenote/src/main/res/layout/style_list_row_publication.xml
  Simplenote/src/main/res/values-night/colors.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
Labels: Part of a WIP Feature, [status] needs code review

#1135 Remove trailing whitespaces from Fastfile
  fastlane/Fastfile
Labels: tooling

#1136 Add Style Setting (Part 6)
  Simplenote/src/main/java/com/automattic/simplenote/StyleActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/PrefUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ThemeUtils.java
  Simplenote/src/main/res/drawable/bg_list_matrix.xml
  Simplenote/src/main/res/drawable/bg_list_style_matrix.xml
  Simplenote/src/main/res/layout/style_list_row_matrix.xml
  Simplenote/src/main/res/values-night/colors.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
Labels: Part of a WIP Feature, [status] needs code review
