Repository Automattic/simplenote-android, pull requests merged in 2020-12, with the labels that each got.

#1216 Rename the installDeps gradle task to configureApply
  build.gradle
Labels: tooling

#1202 Add Tablet Dimensions
  Simplenote/src/main/res/layout/style_list_row_black.xml
  Simplenote/src/main/res/layout/style_list_row_default.xml
  Simplenote/src/main/res/layout/style_list_row_matrix.xml
  Simplenote/src/main/res/layout/style_list_row_mono.xml
  Simplenote/src/main/res/layout/style_list_row_publication.xml
  Simplenote/src/main/res/layout/style_list_row_sepia.xml
  Simplenote/src/main/res/values-large/dimens.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/strings.xml
Labels: Part of a WIP Feature, [status] needs code review, [status] needs design review

#1112 Issue/1111 rename tag duplicate
  Simplenote/src/main/java/com/automattic/simplenote/TagDialogFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/models/Tag.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/TagUtils.java
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, bug

#1225 Crash Device Language Change
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
Labels: [status] needs code review, crash

#1218 Update Tag Hash
  Simplenote/src/main/java/com/automattic/simplenote/utils/TagUtils.java
Labels: task

#1217 Crash Recent Searches
  Simplenote/src/main/java/com/automattic/simplenote/models/Preferences.java
Labels: crash

#1215 Add Analytics Tracking
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/analytics/AnalyticsTracker.java
Labels: analytics

#1224 Add Delete Action
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/NoteUtils.java
  Simplenote/src/main/res/menu/note_editor.xml
  Simplenote/src/main/res/menu/note_markdown.xml
  Simplenote/src/main/res/menu/notes_list.xml
  Simplenote/src/main/res/values/strings.xml
Labels: task

#1226 Add Dialog Utils
  Simplenote/src/main/java/com/automattic/simplenote/TagDialogFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DialogUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/NoteUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/TagsMultiAutoCompleteTextView.java
  Simplenote/src/main/res/values/strings.xml
Labels: debt

#1230 Enable Installable Builds
  .circleci/config.yml
Labels: Releases, [status] needs code review

#1228 Crash Rename Tag
  Simplenote/src/main/java/com/automattic/simplenote/TagDialogFragment.java
  Simplenote/src/main/res/layout/edit_tag.xml
  Simplenote/src/main/res/values/strings.xml
Labels: crash

#1229 Right Arrow Hardware Keyboard Key Blanks Out Note Editor
  Simplenote/src/main/java/com/automattic/simplenote/widgets/NoteEditorViewPager.java
Labels: [status] needs code review, bug

#1232 Update Simperium Dimensions
  Simplenote/src/main/res/layout/activity_note_editor.xml
  Simplenote/src/main/res/layout/edit_tag.xml
Labels: [status] needs code review, debt

#1234 Update Simperium References
  Simplenote/src/main/res/layout/fragment_about.xml
  Simplenote/src/main/res/layout/style_list_row_black.xml
  Simplenote/src/main/res/layout/style_list_row_default.xml
  Simplenote/src/main/res/layout/style_list_row_matrix.xml
  Simplenote/src/main/res/layout/style_list_row_mono.xml
  Simplenote/src/main/res/layout/style_list_row_publication.xml
  Simplenote/src/main/res/layout/style_list_row_sepia.xml
  Simplenote/src/main/res/values-large/dimens.xml
  Simplenote/src/main/res/values/dimens.xml
Labels: [status] needs code review, debt

#1233 Update Password Policy
  Simplenote/build.gradle
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, enhancement

#1235 Update Internote Autocomplete
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
Labels: [status] needs code review, enhancement

#1236 Make sure that the cursor doesn't get hidden behind the search results bar
  Simplenote/src/main/res/layout/activity_note_editor.xml
Labels: [status] needs code review, bug

#1238 Issue/1222 long tag drawer
  Simplenote/src/main/res/layout/activity_notes.xml
  Simplenote/src/main/res/values/styles.xml
Labels: [status] needs code review, enhancement

#1237 Fix the issue of adding checkboxes to long lines
  Simplenote/src/main/java/com/automattic/simplenote/widgets/SimplenoteEditText.java
Labels: [status] needs code review, bug

#1241 Add Heartbeat Listener
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/Simplenote.java
Labels: [status] needs code review, enhancement

#1240 Fix search of terms containing dash character
  Simplenote/src/main/java/com/automattic/simplenote/utils/SearchTokenizer.java
Labels: [status] needs code review, bug

#1244 Update Padding Preference
  Simplenote/src/main/res/layout/preference_button.xml
  Simplenote/src/main/res/layout/preference_default.xml
  Simplenote/src/main/res/values-large/dimens.xml
  Simplenote/src/main/res/values/dimens.xml
Labels: bug

#1243 Update Information Sheet
  Simplenote/src/main/res/layout/bottom_sheet_info.xml
  Simplenote/src/main/res/layout/reference_list_row.xml
  Simplenote/src/main/res/values/dimens.xml
Labels: enhancement

#1247 Make the note preview mobile friendly
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
Labels: bug

#1242 Select next note after trashing/restoring a note in tablet landscape
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/NoteUtils.java
Labels: [status] needs code review, enhancement

#1248 Attempt to fix the duplication of shared notes
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: [status] needs code review, bug

#1253 Improve theme and style changes handling
  Simplenote/src/main/java/com/automattic/simplenote/AboutActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/StyleActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/ThemedAppCompatActivity.java
Labels: [status] needs code review, bug

#1256 Add more tests to NoteTest and NoteIndexerTest
  Simplenote/src/androidTest/java/com/automattic/simplenote/models/NoteIndexerTest.java
  Simplenote/src/androidTest/java/com/automattic/simplenote/models/NoteTest.java
Labels: [status] needs code review, task

#1257 Test 1256
  Simplenote/src/androidTest/java/com/automattic/simplenote/models/NoteIndexerTest.java
  Simplenote/src/androidTest/java/com/automattic/simplenote/models/NoteTest.java
Labels: Part of a WIP Feature

#1255 Add Sync Worker
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/Simplenote.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/SyncWorker.java
Labels: task
