Repository Automattic/simplenote-android, pull requests merged in 2020-02, with the labels that each got.

#929 Note Options History
  Simplenote/src/main/java/com/automattic/simplenote/HistoryBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DateTimeUtils.java
  Simplenote/src/main/res/color/accent_text_button_disabled_selector.xml
  Simplenote/src/main/res/layout/bottom_sheet_history.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/styles.xml
Labels: [status] needs code review, enhancement

#932 Note Options Information
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/InfoBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/res/layout/bottom_sheet_history.xml
  Simplenote/src/main/res/layout/bottom_sheet_info.xml
  Simplenote/src/main/res/menu/note_editor.xml
  Simplenote/src/main/res/menu/note_markdown.xml
  Simplenote/src/main/res/menu/notes_list.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
Labels: [status] needs code review, enhancement

#933 Update Bottom Sheet
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/BottomSheetDialogBase.java
  Simplenote/src/main/java/com/automattic/simplenote/HistoryBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/InfoBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/ShareBottomSheetDialog.java
Labels: [status] needs code review, bug

#930 Update App Store description
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/full_description.txt
  Simplenote/metadata/short_description.txt
Labels: tooling

#931 Update/play store description 2
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/full_description.txt
  Simplenote/metadata/short_description.txt
Labels: tooling

#934 Note Options Menu
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DrawableUtils.java
  Simplenote/src/main/res/layout/activity_note_editor.xml
  Simplenote/src/main/res/menu/bulk_edit.xml
  Simplenote/src/main/res/menu/note_editor.xml
  Simplenote/src/main/res/menu/note_markdown.xml
  Simplenote/src/main/res/menu/notes_list.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, [status] needs design review, enhancement

#935 Merge Release/2.3 into develop
  Simplenote/build.gradle
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-cy/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/88.txt
  fastlane/metadata/android/ar/changelogs/93.txt
  fastlane/metadata/android/de-DE/changelogs/88.txt
  fastlane/metadata/android/de-DE/changelogs/93.txt
  fastlane/metadata/android/es-ES/changelogs/88.txt
  fastlane/metadata/android/es-ES/changelogs/93.txt
  fastlane/metadata/android/fr-FR/changelogs/88.txt
  fastlane/metadata/android/fr-FR/changelogs/93.txt
  fastlane/metadata/android/id/changelogs/88.txt
  fastlane/metadata/android/id/changelogs/93.txt
  fastlane/metadata/android/it-IT/changelogs/88.txt
  fastlane/metadata/android/it-IT/changelogs/93.txt
  fastlane/metadata/android/iw-IL/changelogs/88.txt
  fastlane/metadata/android/iw-IL/changelogs/93.txt
  fastlane/metadata/android/ja-JP/changelogs/88.txt
  fastlane/metadata/android/ja-JP/changelogs/93.txt
  fastlane/metadata/android/ko-KR/changelogs/88.txt
  fastlane/metadata/android/ko-KR/changelogs/93.txt
  fastlane/metadata/android/nl-NL/changelogs/88.txt
  fastlane/metadata/android/nl-NL/changelogs/93.txt
  fastlane/metadata/android/pt-BR/changelogs/88.txt
  fastlane/metadata/android/pt-BR/changelogs/93.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/88.txt
  fastlane/metadata/android/ru-RU/changelogs/93.txt
  fastlane/metadata/android/sv-SE/changelogs/88.txt
  fastlane/metadata/android/sv-SE/changelogs/93.txt
  fastlane/metadata/android/tr-TR/changelogs/88.txt
  fastlane/metadata/android/tr-TR/changelogs/93.txt
  fastlane/metadata/android/zh-CN/changelogs/88.txt
  fastlane/metadata/android/zh-CN/changelogs/93.txt
  fastlane/metadata/android/zh-TW/changelogs/88.txt
  fastlane/metadata/android/zh-TW/changelogs/93.txt
Labels: release

#936 Merge release 2.3 into master
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/HistoryBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/InfoBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DateTimeUtils.java
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-cy/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/88.txt
  fastlane/metadata/android/ar/changelogs/93.txt
  fastlane/metadata/android/de-DE/changelogs/88.txt
  fastlane/metadata/android/de-DE/changelogs/93.txt
  fastlane/metadata/android/es-ES/changelogs/88.txt
  fastlane/metadata/android/es-ES/changelogs/93.txt
  fastlane/metadata/android/fr-FR/changelogs/88.txt
  fastlane/metadata/android/fr-FR/changelogs/93.txt
  fastlane/metadata/android/id/changelogs/88.txt
  fastlane/metadata/android/id/changelogs/93.txt
  fastlane/metadata/android/it-IT/changelogs/88.txt
  fastlane/metadata/android/it-IT/changelogs/93.txt
  fastlane/metadata/android/iw-IL/changelogs/88.txt
  fastlane/metadata/android/iw-IL/changelogs/93.txt
  fastlane/metadata/android/ja-JP/changelogs/88.txt
  fastlane/metadata/android/ja-JP/changelogs/93.txt
  fastlane/metadata/android/ko-KR/changelogs/88.txt
  fastlane/metadata/android/ko-KR/changelogs/93.txt
  fastlane/metadata/android/nl-NL/changelogs/88.txt
  fastlane/metadata/android/nl-NL/changelogs/93.txt
  fastlane/metadata/android/pt-BR/changelogs/88.txt
  fastlane/metadata/android/pt-BR/changelogs/93.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/88.txt
  fastlane/metadata/android/ru-RU/changelogs/93.txt
  fastlane/metadata/android/sv-SE/changelogs/88.txt
  fastlane/metadata/android/sv-SE/changelogs/93.txt
  fastlane/metadata/android/tr-TR/changelogs/88.txt
  fastlane/metadata/android/tr-TR/changelogs/93.txt
  fastlane/metadata/android/zh-CN/changelogs/88.txt
  fastlane/metadata/android/zh-CN/changelogs/93.txt
  fastlane/metadata/android/zh-TW/changelogs/88.txt
  fastlane/metadata/android/zh-TW/changelogs/93.txt
Labels: release

#937 Feature/move note options
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/InfoBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DrawableUtils.java
  Simplenote/src/main/res/layout/activity_note_editor.xml
  Simplenote/src/main/res/layout/bottom_sheet_history.xml
  Simplenote/src/main/res/layout/bottom_sheet_info.xml
  Simplenote/src/main/res/menu/bulk_edit.xml
  Simplenote/src/main/res/menu/note_editor.xml
  Simplenote/src/main/res/menu/note_markdown.xml
  Simplenote/src/main/res/menu/notes_list.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
Labels: [status] needs code review, enhancement

#938 Update shield for 2.3
  README.md
Labels: release

#939 Merge Release/2.4 into Develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
Labels: release

#944 Merge Hotfix/2.3.1 into Master
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/utils/DateTimeUtils.java
Labels: release

#940 Note Options Snackbar
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/SnackbarUtils.java
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, enhancement

#946 Remove Passcode Logout
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
Labels: [status] needs code review, bug

#942 Send 2.4 release notes for translation.
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
Labels: release

#941 Merge Release/2.4 into develop
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
Labels: release

#950 Crash Markdown Options
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
Labels: [status] needs code review, crash

#949 Crash Tablet Widget
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidget.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetConfigureActivity.java
Labels: [status] needs code review, crash

#953 Merge Release/2.4 into develop
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidget.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetConfigureActivity.java
Labels: release

#947 Add Dark Widget
  RELEASE-NOTES.txt
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetDark.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetDarkConfigureActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetLight.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetLightConfigureActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/WidgetUtils.java
  Simplenote/src/main/res/drawable-nodpi/note_widget_preview.png
  Simplenote/src/main/res/drawable-nodpi/note_widget_preview_dark.png
  Simplenote/src/main/res/drawable-nodpi/note_widget_preview_light.png
  Simplenote/src/main/res/drawable/note_widget_background_dark.xml
  Simplenote/src/main/res/drawable/note_widget_background_light.xml
  Simplenote/src/main/res/layout/note_widget_dark.xml
  Simplenote/src/main/res/layout/note_widget_light.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/xml/note_widget_info_dark.xml
  Simplenote/src/main/res/xml/note_widget_info_light.xml
Labels: [status] needs code review, enhancement

#954 Update Widget Checklist
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetDark.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetDarkConfigureActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetLight.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetLightConfigureActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ChecklistUtils.java
Labels: [status] needs code review, enhancement

#955 Issue/952 search highlighting checklists
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/utils/ChecklistUtils.java
Labels: [status] needs code review, bug

#957 Issue/956 disable hiding bar
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/res/layout-large-land/fragment_note_editor.xml
  Simplenote/src/main/res/layout/activity_note_editor.xml
Labels: [status] needs code review, [status] needs design review, bug, enhancement

#960 Issue/884 app starts with white background in dark theme
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/Simplenote.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/ThemedAppCompatActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ThemeUtils.java
  Simplenote/src/main/res/drawable/splash_background.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values-v27/styles.xml
  Simplenote/src/main/res/values/styles.xml
Labels: enhancement

#958 Note List Widget
  RELEASE-NOTES.txt
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListWidgetDark.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListWidgetDarkService.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListWidgetFactory.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListWidgetLight.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListWidgetLightService.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/analytics/AnalyticsTracker.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/WidgetUtils.java
  Simplenote/src/main/res/drawable-nodpi/note_list_widget_preview_dark.png
  Simplenote/src/main/res/drawable-nodpi/note_list_widget_preview_light.png
  Simplenote/src/main/res/drawable/bg_list_popup.xml
  Simplenote/src/main/res/drawable/bg_ripple_oval_blue_dark.xml
  Simplenote/src/main/res/drawable/bg_ripple_oval_blue_light.xml
  Simplenote/src/main/res/drawable/note_widget_background_dark.xml
  Simplenote/src/main/res/drawable/note_widget_background_light.xml
  Simplenote/src/main/res/layout/note_list_widget_dark.xml
  Simplenote/src/main/res/layout/note_list_widget_item_dark.xml
  Simplenote/src/main/res/layout/note_list_widget_item_light.xml
  Simplenote/src/main/res/layout/note_list_widget_light.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/xml/note_list_widget_info_dark.xml
  Simplenote/src/main/res/xml/note_list_widget_info_light.xml
Labels: [status] needs code review, enhancement

#964 Update Splash Style
  Simplenote/src/main/java/com/automattic/simplenote/Simplenote.java
  Simplenote/src/main/java/com/automattic/simplenote/ThemedAppCompatActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ThemeUtils.java
  Simplenote/src/main/res/drawable/bg_splash.xml
  Simplenote/src/main/res/drawable/splash_background.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values-v27/styles.xml
  Simplenote/src/main/res/values/styles.xml
Labels: [status] needs code review, debt

#962 Add Animated Actions
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/res/drawable/av_checklist_24dp.xml
  Simplenote/src/main/res/drawable/av_info_24dp.xml
  Simplenote/src/main/res/drawable/av_list_hide_show_24dp.xml
  Simplenote/src/main/res/drawable/av_list_show_hide_24dp.xml
  Simplenote/src/main/res/drawable/av_trash_empty_24dp.xml
  Simplenote/src/main/res/drawable/av_visibility_off_on_24dp.xml
  Simplenote/src/main/res/drawable/av_visibility_on_off_24dp.xml
  Simplenote/src/main/res/drawable/ic_trash_disabled_24dp.xml
  Simplenote/src/main/res/drawable/ic_trash_selector.xml
  Simplenote/src/main/res/drawable/ic_visibility_off_24dp.xml
  Simplenote/src/main/res/menu/note_editor.xml
  Simplenote/src/main/res/menu/notes_list.xml
  Simplenote/src/main/res/values/integers.xml
  Simplenote/src/main/res/values/strings.xml
Labels: enhancement

#963 Update Widget Preview
  Simplenote/src/main/res/drawable-nodpi/note_widget_preview_dark.png
  Simplenote/src/main/res/drawable-nodpi/note_widget_preview_light.png
Labels: [status] needs code review, [status] needs design review, enhancement

#961 Add RTL Support
  RELEASE-NOTES.txt
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/res/layout-large-land/fragment_note_editor.xml
  Simplenote/src/main/res/layout/fragment_note_editor.xml
Labels: i18n
