Repository Automattic/simplenote-android, pull requests merged in 2020-07, with the labels that each got.

#1086 Merge 2.7.1 hotfix in 2.8.0 with conflict resolution
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/AboutFragment.java
  Simplenote/src/main/res/layout/fragment_about.xml
  Simplenote/src/main/res/values/strings.xml
Labels: Releases

#1084 Merge hotfix release 2.7.1 into 2.8.0
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/AboutFragment.java
  Simplenote/src/main/res/layout/fragment_about.xml
  Simplenote/src/main/res/values/strings.xml
Labels: Releases

#1088 Switch to dedicated file on develop to upload strings for translation
  fastlane/Fastfile
  fastlane/resources/values/strings.xml
Labels: tooling

#1081 Merge 2.8-rc-2 into master
  .configure
  .configure-files/automattic.jks.enc
  .configure-files/debug.keystore.enc
  .configure-files/gradle.properties.enc
  .gitignore
  Gemfile.lock
  README.md
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  Simplenote/src/androidTest/java/com/automattic/simplenote/screenshots/ScreenshotTest.java
  Simplenote/src/main/assets/dark.css
  Simplenote/src/main/assets/light.css
  Simplenote/src/main/java/com/automattic/simplenote/AboutFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/HistoryBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/InfoBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/ShareBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/ShortcutDialogFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/BrowserUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ChecklistUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/widgets/SimplenoteEditText.java
  Simplenote/src/main/res/drawable/bg_key.xml
  Simplenote/src/main/res/layout/dialog_shortcuts_all.xml
  Simplenote/src/main/res/layout/dialog_shortcuts_editor_edit.xml
  Simplenote/src/main/res/layout/dialog_shortcuts_editor_preview.xml
  Simplenote/src/main/res/layout/dialog_shortcuts_list.xml
  Simplenote/src/main/res/layout/fragment_about.xml
  Simplenote/src/main/res/layout/search_suggestion.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/attrs.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
  build.gradle
  fastlane/Fastfile
  fastlane/Pluginfile
  gradle/wrapper/gradle-wrapper.properties
Labels: Releases

#1011 Add debug option in settings to export notes to JSON file
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/models/Note.java
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/xml/preferences.xml
Labels: [status] needs code review, task

#1091 Remove Travis CI configuration
  .travis.yml
Labels: tooling

#1093 Export Unsynced Notes
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, enhancement

#1094 Update finalize_release lane
  fastlane/Fastfile
Labels: tooling

#1092 Update Rename Tag
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/TagDialogFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/models/NoteTagger.java
  Simplenote/src/main/java/com/automattic/simplenote/models/Tag.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/TagUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/TagsMultiAutoCompleteTextView.java
  Simplenote/src/main/res/layout/edit_tag.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
Labels: bug

#1096 Automatically creates GitHub releases
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: tooling

#1100 Update Tag List
  Simplenote/src/main/java/com/automattic/simplenote/TagsActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsListFragment.java
  Simplenote/src/main/res/layout/activity_tags.xml
  Simplenote/src/main/res/layout/fragment_tags_list.xml
Labels: [status] needs code review, bug, debt

#1098 Update Tag Submission
  Simplenote/src/main/java/com/automattic/simplenote/utils/TagsMultiAutoCompleteTextView.java
  Simplenote/src/main/res/layout-large-land/fragment_note_editor.xml
  Simplenote/src/main/res/layout/fragment_note_editor.xml
Labels: [status] needs code review, enhancement

#1106 Merge release 2.8.0 into develop
  Simplenote/build.gradle
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/106.txt
  fastlane/metadata/android/ar/changelogs/110.txt
  fastlane/metadata/android/de-DE/changelogs/106.txt
  fastlane/metadata/android/de-DE/changelogs/110.txt
  fastlane/metadata/android/es-ES/changelogs/106.txt
  fastlane/metadata/android/es-ES/changelogs/110.txt
  fastlane/metadata/android/fr-FR/changelogs/106.txt
  fastlane/metadata/android/fr-FR/changelogs/110.txt
  fastlane/metadata/android/id/changelogs/106.txt
  fastlane/metadata/android/id/changelogs/110.txt
  fastlane/metadata/android/it-IT/changelogs/106.txt
  fastlane/metadata/android/it-IT/changelogs/110.txt
  fastlane/metadata/android/iw-IL/changelogs/106.txt
  fastlane/metadata/android/iw-IL/changelogs/110.txt
  fastlane/metadata/android/ja-JP/changelogs/106.txt
  fastlane/metadata/android/ja-JP/changelogs/110.txt
  fastlane/metadata/android/ko-KR/changelogs/106.txt
  fastlane/metadata/android/ko-KR/changelogs/110.txt
  fastlane/metadata/android/nl-NL/changelogs/106.txt
  fastlane/metadata/android/nl-NL/changelogs/110.txt
  fastlane/metadata/android/pt-BR/changelogs/106.txt
  fastlane/metadata/android/pt-BR/changelogs/110.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/106.txt
  fastlane/metadata/android/ru-RU/changelogs/110.txt
  fastlane/metadata/android/sv-SE/changelogs/106.txt
  fastlane/metadata/android/sv-SE/changelogs/110.txt
  fastlane/metadata/android/tr-TR/changelogs/106.txt
  fastlane/metadata/android/tr-TR/changelogs/110.txt
  fastlane/metadata/android/zh-CN/changelogs/106.txt
  fastlane/metadata/android/zh-CN/changelogs/110.txt
  fastlane/metadata/android/zh-TW/changelogs/106.txt
  fastlane/metadata/android/zh-TW/changelogs/110.txt
Labels: Releases

#1108 Update README version shield to 2.8
  README.md
Labels: Releases

#1109 Merge 2.9-rc-1 into develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
Labels: Releases

#1103 Update Shortcuts Layouts
  Simplenote/src/main/res/layout/dialog_shortcuts_all.xml
  Simplenote/src/main/res/layout/dialog_shortcuts_editor_edit.xml
  Simplenote/src/main/res/layout/dialog_shortcuts_editor_preview.xml
  Simplenote/src/main/res/layout/dialog_shortcuts_list.xml
  Simplenote/src/main/res/values/styles.xml
Labels: [status] needs code review, debt, i18n

#1110 Add Button Description
  Simplenote/src/main/res/layout/fragment_notes_list.xml
Labels: [status] needs code review, accessibility, debt
