Repository Automattic/simplenote-android, pull requests merged in 2020-01, with the labels that each got.

#921 Set image resource from Fragment
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
Labels: bug

#922 Update Fastlane to 2.140.0
  Gemfile
  Gemfile.lock
Labels: tooling

#924 Diff Match Patch
  Simplenote/build.gradle
Labels: bug

#926 Merge release 2.3 into develop
  Simplenote/build.gradle
Labels: release

#927 Update Websocket Threading
  RELEASE-NOTES.txt
  Simplenote/build.gradle
Labels: [status] needs code review, bug

#928 Update Keypad Layout
  Simplenote/build.gradle
  Simplenote/src/main/res/values/styles.xml
Labels: [status] needs code review, bug
