Repository Automattic/simplenote-android, pull requests merged in 2020-05, with the labels that each got.

#1012 Merge code frozen release 2.6 into develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
Labels: Releases

#1013 Merge code frozen 2.6 into master
  Gemfile.lock
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  Simplenote/src/main/java/com/automattic/simplenote/AboutActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/AboutFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/widgets/SpinningImageButton.java
  Simplenote/src/main/res/drawable-ldrtl/ic_arrow_top_right_24dp.xml
  Simplenote/src/main/res/drawable/ic_arrow_top_right_24dp.xml
  Simplenote/src/main/res/layout-large-land/fragment_note_editor.xml
  Simplenote/src/main/res/layout/fragment_about.xml
  Simplenote/src/main/res/values-night-v27/styles.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values-v27/styles.xml
  Simplenote/src/main/res/values/arrays.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
Labels: Releases

#1014 Routine Ruby tooling update
  .ruby-version
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: tooling

#1019 Use AndroidX version of JUnit in order to run tests again.
  Simplenote/build.gradle
Labels: tooling

#1017 Issue/1015 crash save note
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
Labels: [status] needs code review, crash

#1024 Issue/1020 markdown setting sync
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
Labels: [status] needs code review, bug

#1025 Issue/1023 tablet search list
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: [status] needs code review, bug

#1028 Add Actions Sync
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: [status] needs code review, bug

#1034 Issue/1029 publish network check
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/NetworkUtils.java
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, enhancement

#1010 Update Color 2.3.0
  Simplenote/src/debug/res/mipmap-hdpi/ic_launcher.png
  Simplenote/src/debug/res/mipmap-mdpi/ic_launcher.png
  Simplenote/src/debug/res/mipmap-xhdpi/ic_launcher.png
  Simplenote/src/debug/res/mipmap-xxhdpi/ic_launcher.png
  Simplenote/src/debug/res/mipmap-xxxhdpi/ic_launcher.png
  Simplenote/src/main/assets/dark.css
  Simplenote/src/main/assets/light.css
  Simplenote/src/main/res/layout/fragment_about.xml
  Simplenote/src/main/res/mipmap-hdpi/ic_launcher.png
  Simplenote/src/main/res/mipmap-mdpi/ic_launcher.png
  Simplenote/src/main/res/mipmap-xhdpi/ic_launcher.png
  Simplenote/src/main/res/mipmap-xxhdpi/ic_launcher.png
  Simplenote/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/styles.xml
Labels: [status] needs code review, [status] needs design review, task

#1035 Documentation: Add testing checklist and documentation for testing
  CONTRIBUTING.md
  TESTING-CHECKLIST.md
Labels: enhancement

#1027 Add encrypted credentials for upcoming screenshot user
  .configure
  .configure-files/gradle.properties.enc
  Simplenote/build.gradle
  Simplenote/gradle.properties-example
Labels: tooling

#1037 Update gradle wrapper from to 5.6.4
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: tooling

#1026 Fastlane setup for local screenshot automation
  .gitignore
  Simplenote/build.gradle
  Simplenote/src/androidTest/java/com/automattic/simplenote/screenshots/ScreenshotTest.java
  Simplenote/src/screenshots/AndroidManifest.xml
  fastlane/Fastfile
Labels: tooling

#1039 Update Empty Trash
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: [status] needs code review, bug

#1042 Add App Links
  Simplenote/build.gradle
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, enhancement
