Repository Automattic/simplenote-android, pull requests merged in 2020-04, with the labels that each got.

#1000 Merge Release/2.5 into develop
  README.md
  Simplenote/build.gradle
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-cy/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/101.txt
  fastlane/metadata/android/ar/changelogs/98.txt
  fastlane/metadata/android/de-DE/changelogs/101.txt
  fastlane/metadata/android/de-DE/changelogs/98.txt
  fastlane/metadata/android/es-ES/changelogs/101.txt
  fastlane/metadata/android/es-ES/changelogs/98.txt
  fastlane/metadata/android/fr-FR/changelogs/101.txt
  fastlane/metadata/android/fr-FR/changelogs/98.txt
  fastlane/metadata/android/id/changelogs/101.txt
  fastlane/metadata/android/id/changelogs/98.txt
  fastlane/metadata/android/it-IT/changelogs/101.txt
  fastlane/metadata/android/it-IT/changelogs/98.txt
  fastlane/metadata/android/iw-IL/changelogs/101.txt
  fastlane/metadata/android/iw-IL/changelogs/98.txt
  fastlane/metadata/android/ja-JP/changelogs/101.txt
  fastlane/metadata/android/ja-JP/changelogs/98.txt
  fastlane/metadata/android/ko-KR/changelogs/101.txt
  fastlane/metadata/android/ko-KR/changelogs/98.txt
  fastlane/metadata/android/nl-NL/changelogs/101.txt
  fastlane/metadata/android/nl-NL/changelogs/98.txt
  fastlane/metadata/android/pt-BR/changelogs/101.txt
  fastlane/metadata/android/pt-BR/changelogs/98.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/101.txt
  fastlane/metadata/android/ru-RU/changelogs/98.txt
  fastlane/metadata/android/sv-SE/changelogs/101.txt
  fastlane/metadata/android/sv-SE/changelogs/98.txt
  fastlane/metadata/android/tr-TR/changelogs/101.txt
  fastlane/metadata/android/tr-TR/changelogs/98.txt
  fastlane/metadata/android/zh-CN/changelogs/101.txt
  fastlane/metadata/android/zh-CN/changelogs/98.txt
  fastlane/metadata/android/zh-TW/changelogs/101.txt
  fastlane/metadata/android/zh-TW/changelogs/98.txt
Labels: Releases

#1002 Crash Animated Drawable
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DrawableUtils.java
Labels: [status] needs code review, crash

#1003 Merge Release/2.5.1 into develop
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DrawableUtils.java
Labels: Releases

#1004 Merge Release 2.5.1 into Master
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DrawableUtils.java
Labels: Releases

#998 Update Password Policy
  Simplenote/build.gradle
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, enhancement

#1006 Revert Websocket Threading
  RELEASE-NOTES.txt
  Simplenote/build.gradle
Labels: [status] needs code review, bug

#1009 Update Password Policy
  Simplenote/build.gradle
Labels: [status] needs code review, enhancement
