Repository Automattic/simplenote-android, pull requests merged in 2020-09, with the labels that each got.

#1138 Update Visit Website
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, task

#1141 Merge 2.10 RC into develop
  Gemfile
  Gemfile.lock
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  fastlane/Pluginfile
  fastlane/resources/values/strings.xml
Labels: Releases

#1143 Add Tracking Recent
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/analytics/AnalyticsTracker.java
Labels: [status] needs code review, analytics

#1146 Switch configuration to trunk
  .configure
  Gemfile.lock
Labels: tooling

#1144 Update Search Empty
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/res/layout/empty_view.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/strings.xml
Labels: enhancement

#1145 Add Internote Linking
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/InfoBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/models/Note.java
  Simplenote/src/main/java/com/automattic/simplenote/models/Reference.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/SimplenoteLinkify.java
  Simplenote/src/main/res/drawable/ic_link_24dp.xml
  Simplenote/src/main/res/drawable/ic_note_24dp.xml
  Simplenote/src/main/res/layout/bottom_sheet_info.xml
  Simplenote/src/main/res/layout/reference_list_row.xml
  Simplenote/src/main/res/menu/bulk_edit.xml
  Simplenote/src/main/res/menu/note_editor.xml
  Simplenote/src/main/res/menu/note_markdown.xml
  Simplenote/src/main/res/menu/notes_list.xml
  Simplenote/src/main/res/values/plurals.xml
  Simplenote/src/main/res/values/strings.xml
Labels: enhancement

#1151 Merge release 2.10 into develop
  README.md
  Simplenote/build.gradle
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-cy/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/112.txt
  fastlane/metadata/android/de-DE/changelogs/112.txt
  fastlane/metadata/android/es-ES/changelogs/112.txt
  fastlane/metadata/android/es-ES/changelogs/115.txt
  fastlane/metadata/android/fr-FR/changelogs/112.txt
  fastlane/metadata/android/fr-FR/changelogs/115.txt
  fastlane/metadata/android/id/changelogs/112.txt
  fastlane/metadata/android/it-IT/changelogs/112.txt
  fastlane/metadata/android/it-IT/changelogs/115.txt
  fastlane/metadata/android/iw-IL/changelogs/112.txt
  fastlane/metadata/android/iw-IL/changelogs/115.txt
  fastlane/metadata/android/ja-JP/changelogs/112.txt
  fastlane/metadata/android/ja-JP/changelogs/115.txt
  fastlane/metadata/android/ko-KR/changelogs/112.txt
  fastlane/metadata/android/ko-KR/changelogs/115.txt
  fastlane/metadata/android/nl-NL/changelogs/112.txt
  fastlane/metadata/android/pt-BR/changelogs/112.txt
  fastlane/metadata/android/pt-BR/changelogs/115.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/112.txt
  fastlane/metadata/android/ru-RU/changelogs/115.txt
  fastlane/metadata/android/sv-SE/changelogs/112.txt
  fastlane/metadata/android/sv-SE/changelogs/115.txt
  fastlane/metadata/android/tr-TR/changelogs/112.txt
  fastlane/metadata/android/zh-CN/changelogs/112.txt
  fastlane/metadata/android/zh-TW/changelogs/112.txt
  fastlane/metadata/android/zh-TW/changelogs/115.txt
Labels: Releases

#1152 Issue/1149 remove empty checklist
  Simplenote/src/main/java/com/automattic/simplenote/utils/AutoBullet.java
Labels: [status] needs code review, bug

#1154 Merge release 2.11 into develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
Labels: Releases

#1157 Crash Encode Charset
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/utils/TagUtils.java
Labels: crash

#1164 Merge hotfix 2.10.1 into 2.11
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/utils/TagUtils.java
Labels: Releases

#1155 Add Help Link
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/AboutFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/res/layout/fragment_about.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/xml/preferences.xml
Labels: [status] needs code review, task

#1153 Keyboard Shortcuts Translations
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, i18n
