Repository Automattic/simplenote-android, pull requests merged in 2020-03, with the labels that each got.

#972 Update Title Span
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
Labels: bug

#966 Add Debug Credentials
  .configure-files/gradle.properties.enc
  Simplenote/build.gradle
  Simplenote/gradle.properties-example
  Simplenote/src/main/java/com/automattic/simplenote/SimplenoteCredentialsActivity.java
Labels: [status] needs code review, task

#968 List Widget Padding
  Simplenote/src/main/java/com/automattic/simplenote/NoteListWidgetDark.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListWidgetLight.java
  Simplenote/src/main/res/layout/note_list_widget_dark.xml
  Simplenote/src/main/res/layout/note_list_widget_light.xml
  Simplenote/src/main/res/values/dimens.xml
Labels: [status] needs code review, enhancement

#970 Update Gradle Plugin
  Simplenote/src/main/java/com/automattic/simplenote/utils/ThemeUtils.java
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: [status] needs code review, tooling

#971 Add Tags Search
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/TagsListFragment.java
  Simplenote/src/main/res/layout/tags_list_row.xml
  Simplenote/src/main/res/menu/tags_list.xml
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, enhancement

#973 Search Match Tab
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: [status] needs code review, bug

#969 Issue/564 code inspection warnings
  Simplenote/src/main/java/com/automattic/simplenote/AboutFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/models/Note.java
  Simplenote/src/main/java/com/automattic/simplenote/models/NoteTagger.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ChecklistUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/SearchTokenizer.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/SimplenoteMovementMethod.java
  Simplenote/src/main/java/com/automattic/simplenote/widgets/SimplenoteEditText.java
  Simplenote/src/main/res/drawable-hdpi/menu_dropdown_panel_simplestyle.9.png
  Simplenote/src/main/res/drawable-hdpi/menu_dropdown_panel_simplestyle_dark.9.png
  Simplenote/src/main/res/drawable-mdpi/menu_dropdown_panel_simplestyle.9.png
  Simplenote/src/main/res/drawable-mdpi/menu_dropdown_panel_simplestyle_dark.9.png
  Simplenote/src/main/res/drawable-xhdpi/menu_dropdown_panel_simplestyle.9.png
  Simplenote/src/main/res/drawable-xhdpi/menu_dropdown_panel_simplestyle_dark.9.png
  Simplenote/src/main/res/drawable/passcode_logo.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/drawables.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
Labels: [status] needs code review, debt

#965 Update Menu Case
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsListFragment.java
  Simplenote/src/main/res/menu/bulk_edit.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
Labels: [status] needs code review, task

#976 Update shield for 2.4
  README.md
Labels: Releases

#979 Update Nokogiri
  Gemfile.lock
Labels: tooling

#977 Update Menu Case
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, task

#978 Crash Sheet Debounce
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
Labels: [status] needs code review, crash

#981 Issue/980 checklist removes checkbox
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
Labels: [status] needs code review, bug

#985 Issue/982 crash restore multiple
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: [status] needs code review, crash

#986 Empty Trash Actions
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: [status] needs code review, bug

#987 Save Callback Looper
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: [status] needs code review, bug

#988 Placeholder Touch Through
  Simplenote/src/main/res/layout-large-land/fragment_note_editor.xml
Labels: [status] needs code review, bug

#990 Issue/984 list widget button
  Simplenote/src/main/java/com/automattic/simplenote/NoteListWidgetDark.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListWidgetLight.java
Labels: [status] needs code review, bug

#994 Update About Layout
  Simplenote/src/main/java/com/automattic/simplenote/AboutActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/AboutFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/widgets/SpinningImageButton.java
  Simplenote/src/main/res/drawable-ldrtl/ic_arrow_top_right_24dp.xml
  Simplenote/src/main/res/drawable/ic_arrow_top_right_24dp.xml
  Simplenote/src/main/res/layout/fragment_about.xml
  Simplenote/src/main/res/values-night-v27/styles.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values-v27/styles.xml
  Simplenote/src/main/res/values/arrays.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
Labels: [status] needs code review, enhancement

#993 Issue/991 new note loop
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: [status] needs code review, bug

#997 Merge release 2.5 into develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListWidgetDark.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListWidgetLight.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: Releases

#996 Update Splash Status
  Simplenote/src/main/res/values-v27/styles.xml
  Simplenote/src/main/res/values/styles.xml
Labels: [status] needs code review, bug
