Repository Automattic/simplenote-android, pull requests merged in 2020-10, with the labels that each got.

#1161 Add Internote Autocomplete
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/models/Note.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/LinkTokenizer.java
  Simplenote/src/main/java/com/automattic/simplenote/widgets/SimplenoteEditText.java
  Simplenote/src/main/res/layout/autocomplete_list_item.xml
Labels: [status] needs code review, enhancement

#1167 Merge 2.11 into develop with conflicts resolution
  README.md
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/utils/TagUtils.java
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/es-ES/changelogs/115.txt
  fastlane/metadata/android/es-ES/changelogs/119.txt
  fastlane/metadata/android/fr-FR/changelogs/115.txt
  fastlane/metadata/android/fr-FR/changelogs/119.txt
  fastlane/metadata/android/it-IT/changelogs/115.txt
  fastlane/metadata/android/it-IT/changelogs/119.txt
  fastlane/metadata/android/iw-IL/changelogs/115.txt
  fastlane/metadata/android/iw-IL/changelogs/119.txt
  fastlane/metadata/android/ja-JP/changelogs/115.txt
  fastlane/metadata/android/ko-KR/changelogs/115.txt
  fastlane/metadata/android/pt-BR/changelogs/115.txt
  fastlane/metadata/android/pt-BR/changelogs/119.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/115.txt
  fastlane/metadata/android/ru-RU/changelogs/119.txt
  fastlane/metadata/android/sv-SE/changelogs/115.txt
  fastlane/metadata/android/sv-SE/changelogs/119.txt
  fastlane/metadata/android/zh-TW/changelogs/115.txt
  fastlane/metadata/android/zh-TW/changelogs/119.txt
Labels: Releases

#1168 Merge release 2.12 rc 1 into develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
Labels: Releases

#1170 Update Paused Flag
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
Labels: [status] needs code review, bug

#1160 Feature Merge Conflict
  Simplenote/src/main/res/layout/bottom_sheet_info.xml
  Simplenote/src/main/res/values-night-v27/styles.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values-v27/styles.xml
  Simplenote/src/main/res/values/styles.xml
Labels: Part of a WIP Feature

#1177 Update Sheet Styles
  Simplenote/src/main/java/com/automattic/simplenote/BottomSheetDialogBase.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ThemeUtils.java
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/styles.xml
Labels: Part of a WIP Feature, [status] needs code review

#1178 Remove Information Title
  Simplenote/src/main/res/layout/bottom_sheet_info.xml
Labels: [status] needs code review, task

#1179 Update Snackbar Messages
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, task

#1180 Enforce use of bundle exec in Fastfile
  fastlane/Fastfile
Labels: tooling

#1182 Crash No Webview
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/BrowserUtils.java
  Simplenote/src/main/res/drawable/ic_warning_24dp.xml
  Simplenote/src/main/res/layout-large-land/fragment_note_editor.xml
  Simplenote/src/main/res/layout/fragment_note_error.xml
  Simplenote/src/main/res/layout/fragment_note_markdown.xml
  Simplenote/src/main/res/layout/fragment_note_webview.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, crash

#1184 Update Bucket Lifecycle
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/Simplenote.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsActivity.java
Labels: [status] needs code review, task

#1183 Add Styled Widgets (Part 1)
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetDark.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetDarkConfigureActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetLight.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetLightConfigureActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/PrefUtils.java
  Simplenote/src/main/res/drawable/note_widget_background_dark_black.xml
  Simplenote/src/main/res/drawable/note_widget_background_dark_sepia.xml
  Simplenote/src/main/res/drawable/note_widget_background_light_sepia.xml
  Simplenote/src/main/res/layout/note_widget_dark_black.xml
  Simplenote/src/main/res/layout/note_widget_dark_matrix.xml
  Simplenote/src/main/res/layout/note_widget_dark_mono.xml
  Simplenote/src/main/res/layout/note_widget_dark_publication.xml
  Simplenote/src/main/res/layout/note_widget_dark_sepia.xml
  Simplenote/src/main/res/layout/note_widget_light_mono.xml
  Simplenote/src/main/res/layout/note_widget_light_publication.xml
  Simplenote/src/main/res/layout/note_widget_light_sepia.xml
Labels: Part of a WIP Feature, [status] needs code review

#1187 Merge release 2.12 into develop with manual conflicts resolution
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/123.txt
  fastlane/metadata/android/de-DE/changelogs/123.txt
  fastlane/metadata/android/es-ES/changelogs/119.txt
  fastlane/metadata/android/es-ES/changelogs/123.txt
  fastlane/metadata/android/fr-FR/changelogs/119.txt
  fastlane/metadata/android/fr-FR/changelogs/123.txt
  fastlane/metadata/android/id/changelogs/123.txt
  fastlane/metadata/android/it-IT/changelogs/119.txt
  fastlane/metadata/android/it-IT/changelogs/123.txt
  fastlane/metadata/android/iw-IL/changelogs/119.txt
  fastlane/metadata/android/iw-IL/changelogs/123.txt
  fastlane/metadata/android/ja-JP/changelogs/123.txt
  fastlane/metadata/android/ko-KR/changelogs/123.txt
  fastlane/metadata/android/nl-NL/changelogs/123.txt
  fastlane/metadata/android/pt-BR/changelogs/119.txt
  fastlane/metadata/android/pt-BR/changelogs/123.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/119.txt
  fastlane/metadata/android/ru-RU/changelogs/123.txt
  fastlane/metadata/android/sv-SE/changelogs/119.txt
  fastlane/metadata/android/sv-SE/changelogs/123.txt
  fastlane/metadata/android/tr-TR/changelogs/123.txt
  fastlane/metadata/android/zh-CN/changelogs/123.txt
  fastlane/metadata/android/zh-TW/changelogs/119.txt
  fastlane/metadata/android/zh-TW/changelogs/123.txt
Labels: Releases

#1188 Merge release 2.12 into trunk
  .configure
  .configure-files/gradle.properties.enc
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  Simplenote/src/main/java/com/automattic/simplenote/AboutFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/models/Note.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/LinkTokenizer.java
  Simplenote/src/main/java/com/automattic/simplenote/widgets/SimplenoteEditText.java
  Simplenote/src/main/res/layout/autocomplete_list_item.xml
  Simplenote/src/main/res/layout/fragment_about.xml
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/xml/preferences.xml
  fastlane/metadata/android/ar/changelogs/123.txt
  fastlane/metadata/android/de-DE/changelogs/123.txt
  fastlane/metadata/android/es-ES/changelogs/119.txt
  fastlane/metadata/android/es-ES/changelogs/123.txt
  fastlane/metadata/android/fr-FR/changelogs/119.txt
  fastlane/metadata/android/fr-FR/changelogs/123.txt
  fastlane/metadata/android/id/changelogs/123.txt
  fastlane/metadata/android/it-IT/changelogs/119.txt
  fastlane/metadata/android/it-IT/changelogs/123.txt
  fastlane/metadata/android/iw-IL/changelogs/119.txt
  fastlane/metadata/android/iw-IL/changelogs/123.txt
  fastlane/metadata/android/ja-JP/changelogs/123.txt
  fastlane/metadata/android/ko-KR/changelogs/123.txt
  fastlane/metadata/android/nl-NL/changelogs/123.txt
  fastlane/metadata/android/pt-BR/changelogs/119.txt
  fastlane/metadata/android/pt-BR/changelogs/123.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/119.txt
  fastlane/metadata/android/ru-RU/changelogs/123.txt
  fastlane/metadata/android/sv-SE/changelogs/119.txt
  fastlane/metadata/android/sv-SE/changelogs/123.txt
  fastlane/metadata/android/tr-TR/changelogs/123.txt
  fastlane/metadata/android/zh-CN/changelogs/123.txt
  fastlane/metadata/android/zh-TW/changelogs/119.txt
  fastlane/metadata/android/zh-TW/changelogs/123.txt
  fastlane/resources/values/strings.xml
Labels: Releases
