Repository Automattic/simplenote-android, pull requests merged in 2020-06, with the labels that each got.

#1051 Merge release 2.6 into develop
  README.md
  Simplenote/build.gradle
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-cy/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/101.txt
  fastlane/metadata/android/ar/changelogs/104.txt
  fastlane/metadata/android/de-DE/changelogs/101.txt
  fastlane/metadata/android/de-DE/changelogs/104.txt
  fastlane/metadata/android/es-ES/changelogs/101.txt
  fastlane/metadata/android/es-ES/changelogs/104.txt
  fastlane/metadata/android/fr-FR/changelogs/101.txt
  fastlane/metadata/android/fr-FR/changelogs/104.txt
  fastlane/metadata/android/id/changelogs/101.txt
  fastlane/metadata/android/id/changelogs/104.txt
  fastlane/metadata/android/it-IT/changelogs/101.txt
  fastlane/metadata/android/it-IT/changelogs/104.txt
  fastlane/metadata/android/iw-IL/changelogs/101.txt
  fastlane/metadata/android/iw-IL/changelogs/104.txt
  fastlane/metadata/android/ja-JP/changelogs/101.txt
  fastlane/metadata/android/ja-JP/changelogs/104.txt
  fastlane/metadata/android/ko-KR/changelogs/101.txt
  fastlane/metadata/android/ko-KR/changelogs/104.txt
  fastlane/metadata/android/nl-NL/changelogs/101.txt
  fastlane/metadata/android/nl-NL/changelogs/104.txt
  fastlane/metadata/android/pt-BR/changelogs/101.txt
  fastlane/metadata/android/pt-BR/changelogs/104.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/101.txt
  fastlane/metadata/android/ru-RU/changelogs/104.txt
  fastlane/metadata/android/sv-SE/changelogs/101.txt
  fastlane/metadata/android/sv-SE/changelogs/104.txt
  fastlane/metadata/android/tr-TR/changelogs/101.txt
  fastlane/metadata/android/tr-TR/changelogs/104.txt
  fastlane/metadata/android/zh-CN/changelogs/101.txt
  fastlane/metadata/android/zh-CN/changelogs/104.txt
  fastlane/metadata/android/zh-TW/changelogs/101.txt
  fastlane/metadata/android/zh-TW/changelogs/104.txt
Labels: Releases

#1050 Merge release 2.6 into master
  README.md
  Simplenote/build.gradle
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-cy/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/101.txt
  fastlane/metadata/android/ar/changelogs/104.txt
  fastlane/metadata/android/de-DE/changelogs/101.txt
  fastlane/metadata/android/de-DE/changelogs/104.txt
  fastlane/metadata/android/es-ES/changelogs/101.txt
  fastlane/metadata/android/es-ES/changelogs/104.txt
  fastlane/metadata/android/fr-FR/changelogs/101.txt
  fastlane/metadata/android/fr-FR/changelogs/104.txt
  fastlane/metadata/android/id/changelogs/101.txt
  fastlane/metadata/android/id/changelogs/104.txt
  fastlane/metadata/android/it-IT/changelogs/101.txt
  fastlane/metadata/android/it-IT/changelogs/104.txt
  fastlane/metadata/android/iw-IL/changelogs/101.txt
  fastlane/metadata/android/iw-IL/changelogs/104.txt
  fastlane/metadata/android/ja-JP/changelogs/101.txt
  fastlane/metadata/android/ja-JP/changelogs/104.txt
  fastlane/metadata/android/ko-KR/changelogs/101.txt
  fastlane/metadata/android/ko-KR/changelogs/104.txt
  fastlane/metadata/android/nl-NL/changelogs/101.txt
  fastlane/metadata/android/nl-NL/changelogs/104.txt
  fastlane/metadata/android/pt-BR/changelogs/101.txt
  fastlane/metadata/android/pt-BR/changelogs/104.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/101.txt
  fastlane/metadata/android/ru-RU/changelogs/104.txt
  fastlane/metadata/android/sv-SE/changelogs/101.txt
  fastlane/metadata/android/sv-SE/changelogs/104.txt
  fastlane/metadata/android/tr-TR/changelogs/101.txt
  fastlane/metadata/android/tr-TR/changelogs/104.txt
  fastlane/metadata/android/zh-CN/changelogs/101.txt
  fastlane/metadata/android/zh-CN/changelogs/104.txt
  fastlane/metadata/android/zh-TW/changelogs/101.txt
  fastlane/metadata/android/zh-TW/changelogs/104.txt
Labels: Releases

#1053 Merge release 2.7 (beta 1) into develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
Labels: Releases

#1038 Add logic to automate all required screenshots
  .gitignore
  Simplenote/build.gradle
  Simplenote/src/androidTest/java/com/automattic/simplenote/screenshots/ScreenshotTest.java
  fastlane/Fastfile
Labels: tooling

#1056 Issue/1046 search history padding
  Simplenote/src/main/res/layout/search_suggestion.xml
Labels: [status] needs code review, bug

#1055 Add Keyboard Shortcuts
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/ShortcutDialogFragment.java
  Simplenote/src/main/res/drawable/bg_key.xml
  Simplenote/src/main/res/layout/dialog_shortcuts_all.xml
  Simplenote/src/main/res/layout/dialog_shortcuts_editor_edit.xml
  Simplenote/src/main/res/layout/dialog_shortcuts_editor_preview.xml
  Simplenote/src/main/res/layout/dialog_shortcuts_list.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/attrs.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
Labels: [status] needs code review, enhancement

#1061 Issue/1058 link share text
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
Labels: bug

#1064 Issue/1043 crash web browser
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/AboutFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/BrowserUtils.java
  Simplenote/src/main/res/values/strings.xml
Labels: bug, crash

#1060 Issue/1057 tag sync reverted
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
Labels: [status] needs code review, bug

#1063 Issue/1031 note list resize
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: [status] needs code review, bug

#1054 Merge release 2.7 (beta 1) into master
  .configure
  .configure-files/gradle.properties.enc
  .gitignore
  .ruby-version
  CONTRIBUTING.md
  Gemfile.lock
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/gradle.properties-example
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  Simplenote/src/androidTest/java/com/automattic/simplenote/screenshots/ScreenshotTest.java
  Simplenote/src/debug/res/mipmap-hdpi/ic_launcher.png
  Simplenote/src/debug/res/mipmap-mdpi/ic_launcher.png
  Simplenote/src/debug/res/mipmap-xhdpi/ic_launcher.png
  Simplenote/src/debug/res/mipmap-xxhdpi/ic_launcher.png
  Simplenote/src/debug/res/mipmap-xxxhdpi/ic_launcher.png
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/assets/dark.css
  Simplenote/src/main/assets/light.css
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/NetworkUtils.java
  Simplenote/src/main/res/layout/fragment_about.xml
  Simplenote/src/main/res/mipmap-hdpi/ic_launcher.png
  Simplenote/src/main/res/mipmap-mdpi/ic_launcher.png
  Simplenote/src/main/res/mipmap-xhdpi/ic_launcher.png
  Simplenote/src/main/res/mipmap-xxhdpi/ic_launcher.png
  Simplenote/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
  Simplenote/src/screenshots/AndroidManifest.xml
  TESTING-CHECKLIST.md
  build.gradle
  fastlane/Fastfile
  fastlane/Pluginfile
  gradle/wrapper/gradle-wrapper.properties
Labels: Releases

#1067 Issue/1030 bottom sheet resize
  Simplenote/src/main/java/com/automattic/simplenote/HistoryBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/InfoBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/ShareBottomSheetDialog.java
Labels: [status] needs code review, bug

#1068 Update Gradle Plugin
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: [status] needs code review, tooling

#1072 Fixed where Preview tab did not reload changes from Edit tab (#1070)
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
Labels: [status] needs code review, bug

#1074 Switch to a shared debug keystore
  .configure
  .configure-files/automattic.jks.enc
  .configure-files/debug.keystore.enc
  .configure-files/gradle.properties.enc
  Gemfile.lock
  Simplenote/build.gradle
  build.gradle
  fastlane/Pluginfile
Labels: tooling

#1075 Added RTL Mardown Preview Support
  RELEASE-NOTES.txt
  Simplenote/src/main/assets/dark.css
  Simplenote/src/main/assets/light.css
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ChecklistUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/widgets/SimplenoteEditText.java
Labels: bug

#1076 Merge release 2.7 into develop
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-cy/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/104.txt
  fastlane/metadata/android/ar/changelogs/106.txt
  fastlane/metadata/android/de-DE/changelogs/104.txt
  fastlane/metadata/android/de-DE/changelogs/106.txt
  fastlane/metadata/android/es-ES/changelogs/104.txt
  fastlane/metadata/android/es-ES/changelogs/106.txt
  fastlane/metadata/android/fr-FR/changelogs/104.txt
  fastlane/metadata/android/fr-FR/changelogs/106.txt
  fastlane/metadata/android/id/changelogs/104.txt
  fastlane/metadata/android/id/changelogs/106.txt
  fastlane/metadata/android/it-IT/changelogs/104.txt
  fastlane/metadata/android/it-IT/changelogs/106.txt
  fastlane/metadata/android/iw-IL/changelogs/104.txt
  fastlane/metadata/android/iw-IL/changelogs/106.txt
  fastlane/metadata/android/ja-JP/changelogs/104.txt
  fastlane/metadata/android/ja-JP/changelogs/106.txt
  fastlane/metadata/android/ko-KR/changelogs/104.txt
  fastlane/metadata/android/ko-KR/changelogs/106.txt
  fastlane/metadata/android/nl-NL/changelogs/104.txt
  fastlane/metadata/android/nl-NL/changelogs/106.txt
  fastlane/metadata/android/pt-BR/changelogs/104.txt
  fastlane/metadata/android/pt-BR/changelogs/106.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/104.txt
  fastlane/metadata/android/ru-RU/changelogs/106.txt
  fastlane/metadata/android/sv-SE/changelogs/104.txt
  fastlane/metadata/android/sv-SE/changelogs/106.txt
  fastlane/metadata/android/tr-TR/changelogs/104.txt
  fastlane/metadata/android/tr-TR/changelogs/106.txt
  fastlane/metadata/android/zh-CN/changelogs/104.txt
  fastlane/metadata/android/zh-CN/changelogs/106.txt
  fastlane/metadata/android/zh-TW/changelogs/104.txt
  fastlane/metadata/android/zh-TW/changelogs/106.txt
Labels: Releases

#1077 Merge release 2.7 into master
  Simplenote/build.gradle
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-cy/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/104.txt
  fastlane/metadata/android/ar/changelogs/106.txt
  fastlane/metadata/android/de-DE/changelogs/104.txt
  fastlane/metadata/android/de-DE/changelogs/106.txt
  fastlane/metadata/android/es-ES/changelogs/104.txt
  fastlane/metadata/android/es-ES/changelogs/106.txt
  fastlane/metadata/android/fr-FR/changelogs/104.txt
  fastlane/metadata/android/fr-FR/changelogs/106.txt
  fastlane/metadata/android/id/changelogs/104.txt
  fastlane/metadata/android/id/changelogs/106.txt
  fastlane/metadata/android/it-IT/changelogs/104.txt
  fastlane/metadata/android/it-IT/changelogs/106.txt
  fastlane/metadata/android/iw-IL/changelogs/104.txt
  fastlane/metadata/android/iw-IL/changelogs/106.txt
  fastlane/metadata/android/ja-JP/changelogs/104.txt
  fastlane/metadata/android/ja-JP/changelogs/106.txt
  fastlane/metadata/android/ko-KR/changelogs/104.txt
  fastlane/metadata/android/ko-KR/changelogs/106.txt
  fastlane/metadata/android/nl-NL/changelogs/104.txt
  fastlane/metadata/android/nl-NL/changelogs/106.txt
  fastlane/metadata/android/pt-BR/changelogs/104.txt
  fastlane/metadata/android/pt-BR/changelogs/106.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/104.txt
  fastlane/metadata/android/ru-RU/changelogs/106.txt
  fastlane/metadata/android/sv-SE/changelogs/104.txt
  fastlane/metadata/android/sv-SE/changelogs/106.txt
  fastlane/metadata/android/tr-TR/changelogs/104.txt
  fastlane/metadata/android/tr-TR/changelogs/106.txt
  fastlane/metadata/android/zh-CN/changelogs/104.txt
  fastlane/metadata/android/zh-CN/changelogs/106.txt
  fastlane/metadata/android/zh-TW/changelogs/104.txt
  fastlane/metadata/android/zh-TW/changelogs/106.txt
Labels: Releases

#1078 Update version to 2.7 in README shield (develop only)
  README.md
Labels: Releases

#1080 Merge 2.8-rc1 into develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
Labels: Releases

#1082 Add california privacy
  Simplenote/src/main/java/com/automattic/simplenote/AboutFragment.java
  Simplenote/src/main/res/layout/fragment_about.xml
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, enhancement
