Repository Automattic/simplenote-android, pull requests merged in 2021-01, with the labels that each got.

#1261 Fix for having a wrong them in the webviews when the app is launched from the widget
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/ThemedAppCompatActivity.java
Labels: [status] needs code review, bug

#1260 Reset the buckets if the user is unauthenticated
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/AuthUtils.java
Labels: [status] needs code review, bug

#1204 Add Add Tag
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/AddTagActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/AniUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DisplayUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/TagUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/widgets/MorphCircleToRectangle.java
  Simplenote/src/main/java/com/automattic/simplenote/widgets/MorphDrawable.java
  Simplenote/src/main/java/com/automattic/simplenote/widgets/MorphRectangleToCircle.java
  Simplenote/src/main/java/com/automattic/simplenote/widgets/MorphSetup.java
  Simplenote/src/main/res/animator/button_raise.xml
  Simplenote/src/main/res/drawable/bg_ripple_oval_fab_color.xml
  Simplenote/src/main/res/layout/activity_tag_add.xml
  Simplenote/src/main/res/layout/activity_tags.xml
  Simplenote/src/main/res/layout/empty_view.xml
  Simplenote/src/main/res/values-night-v27/styles.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values-v27/styles.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
Labels: task

#1264 Add Sync Persistence
  Simplenote/src/main/java/com/automattic/simplenote/InfoBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/LastSyncTimeCache.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/Simplenote.java
  Simplenote/src/main/java/com/automattic/simplenote/SyncTimes.java
  Simplenote/src/main/java/com/automattic/simplenote/ThemedAppCompatActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/AuthUtils.java
Labels: [status] needs code review, enhancement

#1140 WIP: Add new last-sync time indicator
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/InfoBottomSheetDialog.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/Simplenote.java
  Simplenote/src/main/java/com/automattic/simplenote/SyncTimes.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/models/NoteTagger.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/AuthUtils.java
  Simplenote/src/main/res/layout/bottom_sheet_info.xml
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, task

#1269 Merge release 2.14 into develop
  README.md
  Simplenote/build.gradle
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/125.txt
  fastlane/metadata/android/ar/changelogs/127.txt
  fastlane/metadata/android/de-DE/changelogs/125.txt
  fastlane/metadata/android/de-DE/changelogs/127.txt
  fastlane/metadata/android/es-ES/changelogs/125.txt
  fastlane/metadata/android/es-ES/changelogs/127.txt
  fastlane/metadata/android/fr-FR/changelogs/125.txt
  fastlane/metadata/android/fr-FR/changelogs/127.txt
  fastlane/metadata/android/id/changelogs/125.txt
  fastlane/metadata/android/id/changelogs/127.txt
  fastlane/metadata/android/it-IT/changelogs/125.txt
  fastlane/metadata/android/it-IT/changelogs/127.txt
  fastlane/metadata/android/iw-IL/changelogs/125.txt
  fastlane/metadata/android/iw-IL/changelogs/127.txt
  fastlane/metadata/android/ja-JP/changelogs/125.txt
  fastlane/metadata/android/ja-JP/changelogs/127.txt
  fastlane/metadata/android/ko-KR/changelogs/125.txt
  fastlane/metadata/android/ko-KR/changelogs/127.txt
  fastlane/metadata/android/nl-NL/changelogs/125.txt
  fastlane/metadata/android/nl-NL/changelogs/127.txt
  fastlane/metadata/android/pt-BR/changelogs/125.txt
  fastlane/metadata/android/pt-BR/changelogs/127.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/125.txt
  fastlane/metadata/android/ru-RU/changelogs/127.txt
  fastlane/metadata/android/sv-SE/changelogs/125.txt
  fastlane/metadata/android/sv-SE/changelogs/127.txt
  fastlane/metadata/android/tr-TR/changelogs/125.txt
  fastlane/metadata/android/tr-TR/changelogs/127.txt
  fastlane/metadata/android/zh-CN/changelogs/125.txt
  fastlane/metadata/android/zh-CN/changelogs/127.txt
  fastlane/metadata/android/zh-TW/changelogs/125.txt
  fastlane/metadata/android/zh-TW/changelogs/127.txt
Labels: Releases

#1266 Show the current note when rotating to portrait mode on large devices
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
Labels: [status] needs code review, bug

#1267 Fix the issue of not showing the widget configuration screen when applock is enabled
  Simplenote/src/main/java/com/automattic/simplenote/Simplenote.java
  Simplenote/src/main/java/com/automattic/simplenote/SimplenoteAppLock.java
Labels: [status] needs code review, bug

#1249 Display a hint in the navigation menu if the tags list is empty
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/res/layout/activity_notes.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, enhancement

#1271 Merge release 2.15 RC 1 into develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
Labels: Releases

#1273 Update Style Visibility
  Simplenote/src/main/res/xml/preferences.xml
Labels: [status] needs code review, task

#1274 Merge version 2.15 RC 2 into develop
  Simplenote/build.gradle
  Simplenote/src/main/res/xml/preferences.xml
Labels: Releases

#1275 [Platform] Update ReleaseToolkit to 0.12 to fix nokogiri vulnerability
  Gemfile.lock
  fastlane/Pluginfile
Labels: tooling

#1276 Update release-toolkit to 0.13.0
  Gemfile.lock
  fastlane/Pluginfile
  tools/release-checks.sh
Labels: tooling

#1277 Add Email Verification
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/FullScreenDialogFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/ReviewAccountVerifyEmailFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/Simplenote.java
  Simplenote/src/main/java/com/automattic/simplenote/analytics/AnalyticsTracker.java
  Simplenote/src/main/java/com/automattic/simplenote/models/Account.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/AppLog.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/SyncWorker.java
  Simplenote/src/main/res/anim/full_screen_dialog_fragment_none.xml
  Simplenote/src/main/res/anim/full_screen_dialog_fragment_slide_down.xml
  Simplenote/src/main/res/anim/full_screen_dialog_fragment_slide_up.xml
  Simplenote/src/main/res/drawable/ic_mail_24dp.xml
  Simplenote/src/main/res/layout/fragment_full_screen_dialog.xml
  Simplenote/src/main/res/layout/fragment_review_account_verify_email.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, task

#1280 Merge finalized release 2.15 into develop
  README.md
  Simplenote/build.gradle
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-cy/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/127.txt
  fastlane/metadata/android/de-DE/changelogs/127.txt
  fastlane/metadata/android/es-ES/changelogs/127.txt
  fastlane/metadata/android/es-ES/changelogs/130.txt
  fastlane/metadata/android/fr-FR/changelogs/127.txt
  fastlane/metadata/android/fr-FR/changelogs/130.txt
  fastlane/metadata/android/id/changelogs/127.txt
  fastlane/metadata/android/it-IT/changelogs/127.txt
  fastlane/metadata/android/it-IT/changelogs/130.txt
  fastlane/metadata/android/iw-IL/changelogs/127.txt
  fastlane/metadata/android/iw-IL/changelogs/130.txt
  fastlane/metadata/android/ja-JP/changelogs/127.txt
  fastlane/metadata/android/ko-KR/changelogs/127.txt
  fastlane/metadata/android/nl-NL/changelogs/127.txt
  fastlane/metadata/android/pt-BR/changelogs/127.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/127.txt
  fastlane/metadata/android/ru-RU/changelogs/130.txt
  fastlane/metadata/android/sv-SE/changelogs/127.txt
  fastlane/metadata/android/sv-SE/changelogs/130.txt
  fastlane/metadata/android/tr-TR/changelogs/127.txt
  fastlane/metadata/android/tr-TR/changelogs/130.txt
  fastlane/metadata/android/zh-CN/changelogs/127.txt
  fastlane/metadata/android/zh-TW/changelogs/127.txt
Labels: Releases

#1283 Issue/1279 crash log out
  Simplenote/src/main/java/com/automattic/simplenote/Simplenote.java
Labels: [status] needs code review, crash

#1286 Update Sort Tracking
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/analytics/AnalyticsTracker.java
Labels: analytics

#1288 Merge version 2.16 RC 2 into develop with manual conflicts resolution
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  Simplenote/src/main/java/com/automattic/simplenote/Simplenote.java
  fastlane/resources/values/strings.xml
Labels: Releases
