Repository Automattic/simplenote-android, pull requests merged in 2021-08, with the labels that each got.

#1430 Move secrets debug keystore and Google upload credentials outside of the repository
  .circleci/config.yml
  .configure
  .configure-files/gradle.properties.enc
  .gitignore
  fastlane/Fastfile
Labels: tooling

#1423 Fix for email verification screen appears on accounts verified
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/FullScreenDialogFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/ReviewAccountVerifyEmailFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/Simplenote.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/AccountVerificationWatcher.java
Labels: bug

#1433 Fix out of memory error on CI
  .circleci/config.yml
Labels: tooling

#1436 Update the plus icon to add new notes
  RELEASE-NOTES.txt
  Simplenote/src/main/res/drawable/ic_new_note_24dp.xml
  Simplenote/src/main/res/layout/fragment_notes_list.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_black.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_classic.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_default.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_matrix.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_mono.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_publication.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_sepia.xml
  Simplenote/src/main/res/layout/note_list_widget_light_black.xml
  Simplenote/src/main/res/layout/note_list_widget_light_classic.xml
  Simplenote/src/main/res/layout/note_list_widget_light_default.xml
  Simplenote/src/main/res/layout/note_list_widget_light_matrix.xml
  Simplenote/src/main/res/layout/note_list_widget_light_mono.xml
  Simplenote/src/main/res/layout/note_list_widget_light_publication.xml
  Simplenote/src/main/res/layout/note_list_widget_light_sepia.xml
Labels: consistency

#1437 Merge 2.19 code freeze to develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
Labels: Releases

#1438 Remove sort bar in note lists and trash
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/analytics/AnalyticsTracker.java
  Simplenote/src/main/res/drawable/ic_arrow_down_16dp.xml
  Simplenote/src/main/res/drawable/ic_sort_order_24dp.xml
  Simplenote/src/main/res/layout/sort_bar.xml
Labels: [status] needs code review, [status] needs design review, consistency

#1387 Opt-out from translation for all strings using resource references
  Simplenote/src/main/res/values/strings.xml
Labels: tooling

#1443 Rewrite tag-related activities and fragments in Kotlin
  Simplenote/build.gradle
  Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt
  Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagsActivityTest.kt
  Simplenote/src/main/java/com/automattic/simplenote/AddTagActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/AddTagActivity.kt
  Simplenote/src/main/java/com/automattic/simplenote/TagDialogFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/TagDialogFragment.kt
  Simplenote/src/main/java/com/automattic/simplenote/TagsActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsActivity.kt
  Simplenote/src/main/java/com/automattic/simplenote/utils/BaseExt.kt
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/AddTagViewModelTest.kt
Labels: [status] needs code review, task, debt

#1450 Handle back press button when NoteEditorActivity is the Task Root
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
Labels: [status] needs code review

#1446 Simperium from s3
  Simplenote/build.gradle
Labels: tooling

#1451 Merge 2.19 final to develop
  README.md
  Simplenote/build.gradle
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/138.txt
  fastlane/metadata/android/ar/changelogs/140.txt
  fastlane/metadata/android/de-DE/changelogs/138.txt
  fastlane/metadata/android/de-DE/changelogs/140.txt
  fastlane/metadata/android/es-ES/changelogs/138.txt
  fastlane/metadata/android/es-ES/changelogs/140.txt
  fastlane/metadata/android/fr-FR/changelogs/140.txt
  fastlane/metadata/android/id/changelogs/138.txt
  fastlane/metadata/android/id/changelogs/140.txt
  fastlane/metadata/android/it-IT/changelogs/138.txt
  fastlane/metadata/android/it-IT/changelogs/140.txt
  fastlane/metadata/android/iw-IL/changelogs/140.txt
  fastlane/metadata/android/ja-JP/changelogs/140.txt
  fastlane/metadata/android/ko-KR/changelogs/140.txt
  fastlane/metadata/android/nl-NL/changelogs/140.txt
  fastlane/metadata/android/pt-BR/changelogs/138.txt
  fastlane/metadata/android/pt-BR/changelogs/140.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/140.txt
  fastlane/metadata/android/sv-SE/changelogs/140.txt
  fastlane/metadata/android/tr-TR/changelogs/140.txt
  fastlane/metadata/android/zh-CN/changelogs/138.txt
  fastlane/metadata/android/zh-CN/changelogs/140.txt
  fastlane/metadata/android/zh-TW/changelogs/138.txt
  fastlane/metadata/android/zh-TW/changelogs/140.txt
Labels: Releases

#1453 Add release notes
  RELEASE-NOTES.txt
Labels: task

#1456 Merge 2.20 code freeze to develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
Labels: Releases

#1449 Add unverified account check login response
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/ReviewAccountVerifyEmailFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SimplenoteCredentialsActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/AccountNetworkUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/AccountVerificationEmailHandler.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DeleteAccountRequestHandler.java
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, task, [status] needs design review

#1454 Move scroll setup from view tree updates after the note content refreshes
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
Labels: bug, [status] needs code review

#1455 Remove Travis build shield from README
  README.md
Labels: tooling
