Repository Automattic/simplenote-android, pull requests merged in 2021-04, with the labels that each got.

#1354 Tweak screenshots automation to shot note with links instead of inter-note linking view
  .configure
  .configure-files/gradle.properties.enc
  Gemfile.lock
  Simplenote/src/androidTest/java/com/automattic/simplenote/screenshots/ScreenshotTest.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
Labels: tooling

#1377 Test Checklist: Adding more consistency
  TESTING-CHECKLIST.md
Labels: [feature] checklist

#1376 Setup test dependencies and infrastructure for UI tests
  Simplenote/build.gradle
  Simplenote/src/androidTest/java/com/automattic/simplenote/SimplenoteAppRunner.kt
  Simplenote/src/androidTest/java/com/automattic/simplenote/SimplenoteTest.kt
  Simplenote/src/androidTest/java/com/automattic/simplenote/utils/TestBucket.kt
  build.gradle
Labels: debt, task

#1380 UI Tests for AddTagActivity
  Simplenote/src/androidTest/java/com/automattic/simplenote/BaseUITest.kt
  Simplenote/src/androidTest/java/com/automattic/simplenote/integration/AddTagActivityTest.kt
  Simplenote/src/androidTest/java/com/automattic/simplenote/utils/EspressoUtils.kt
Labels: debt, task

#1382 Cleanup of instrumented tests BaseUITest's useTestBucket
  Simplenote/src/androidTest/java/com/automattic/simplenote/BaseUITest.kt
Labels: debt, task

#1385 Added a `setup` test, asking to sign up using mixed-capitalization
  TESTING-CHECKLIST.md
Labels: [feature] checklist

#1384 UI Tests for TagDialogFragment
  Simplenote/build.gradle
  Simplenote/src/androidTest/java/com/automattic/simplenote/BaseUITest.kt
  Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagDialogFragmentTest.kt
  Simplenote/src/androidTest/java/com/automattic/simplenote/utils/TestBucket.kt
Labels: debt, task

#1389 Add wildcard ignore for .configure-files folder
  .gitignore
Labels: tooling
