Repository Automattic/simplenote-android, pull requests merged in 2021-02, with the labels that each got.

#1298 Update Email Verification
  Simplenote/src/main/java/com/automattic/simplenote/models/Account.java
Labels: [status] needs code review, bug

#1291 Add Dismiss Verify
  Simplenote/src/main/java/com/automattic/simplenote/ReviewAccountVerifyEmailFragment.java
Labels: enhancement

#1302 Crash Empty Trash
  Simplenote/src/main/java/com/automattic/simplenote/utils/DrawableUtils.java
Labels: [status] needs code review, crash

#1301 Crash Tags Edit
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/res/layout/drawer_action_edit.xml
Labels: [status] needs code review, crash

#1305 Update Link Error
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs code review, enhancement

#1300 Add Save Scroll
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/Simplenote.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/AuthUtils.java
Labels: [status] needs code review, task

#1303 Add Logout Account
  Simplenote/src/main/java/com/automattic/simplenote/utils/AuthUtils.java
Labels: bug

#1309 Merge release 2.16 RC 3
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/models/Account.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/AuthUtils.java
Labels: Releases

#1308 Update View Link
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
Labels: [status] needs code review, bug

#1306 Update Sort Tracking
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/analytics/AnalyticsTracker.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/PrefUtils.java
Labels: [status] needs code review, analytics

#1312 Update Icon Background
  Simplenote/src/main/res/drawable-night/ic_launcher_background.xml
Labels: [status] needs code review, [status] needs design review, task

#1313 Merge finalized release 2.16 into develop
  README.md
  Simplenote/build.gradle
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/134.txt
  fastlane/metadata/android/de-DE/changelogs/134.txt
  fastlane/metadata/android/es-ES/changelogs/130.txt
  fastlane/metadata/android/es-ES/changelogs/134.txt
  fastlane/metadata/android/fr-FR/changelogs/130.txt
  fastlane/metadata/android/fr-FR/changelogs/134.txt
  fastlane/metadata/android/id/changelogs/134.txt
  fastlane/metadata/android/it-IT/changelogs/130.txt
  fastlane/metadata/android/it-IT/changelogs/134.txt
  fastlane/metadata/android/iw-IL/changelogs/130.txt
  fastlane/metadata/android/iw-IL/changelogs/134.txt
  fastlane/metadata/android/ja-JP/changelogs/134.txt
  fastlane/metadata/android/ko-KR/changelogs/134.txt
  fastlane/metadata/android/pt-BR/changelogs/134.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/130.txt
  fastlane/metadata/android/ru-RU/changelogs/134.txt
  fastlane/metadata/android/sv-SE/changelogs/130.txt
  fastlane/metadata/android/sv-SE/changelogs/134.txt
  fastlane/metadata/android/tr-TR/changelogs/130.txt
  fastlane/metadata/android/tr-TR/changelogs/134.txt
  fastlane/metadata/android/zh-TW/changelogs/134.txt
Labels: Releases

#1318 Merge release 2.17 RC 1 into develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
Labels: Releases

#1326 Bundler fix
  Gemfile
  Gemfile.lock
Labels: tooling

#1325 Bundler fix
  Gemfile
  Gemfile.lock
Labels: tooling

#1295 Update screenshots automation – 2021/02
  Simplenote/src/androidTest/java/com/automattic/simplenote/screenshots/ScreenshotTest.java
Labels: tooling

#1331 Merge finalized release 2.17 into develop
  .configure
  .configure-files/gradle.properties.enc
  README.md
  Simplenote/build.gradle
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-cy/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/134.txt
  fastlane/metadata/android/ar/changelogs/136.txt
  fastlane/metadata/android/de-DE/changelogs/134.txt
  fastlane/metadata/android/de-DE/changelogs/136.txt
  fastlane/metadata/android/es-ES/changelogs/134.txt
  fastlane/metadata/android/es-ES/changelogs/136.txt
  fastlane/metadata/android/fr-FR/changelogs/134.txt
  fastlane/metadata/android/fr-FR/changelogs/136.txt
  fastlane/metadata/android/id/changelogs/134.txt
  fastlane/metadata/android/id/changelogs/136.txt
  fastlane/metadata/android/it-IT/changelogs/134.txt
  fastlane/metadata/android/it-IT/changelogs/136.txt
  fastlane/metadata/android/iw-IL/changelogs/134.txt
  fastlane/metadata/android/iw-IL/changelogs/136.txt
  fastlane/metadata/android/ja-JP/changelogs/134.txt
  fastlane/metadata/android/ja-JP/changelogs/136.txt
  fastlane/metadata/android/ko-KR/changelogs/134.txt
  fastlane/metadata/android/ko-KR/changelogs/136.txt
  fastlane/metadata/android/nl-NL/changelogs/136.txt
  fastlane/metadata/android/pt-BR/changelogs/134.txt
  fastlane/metadata/android/pt-BR/changelogs/136.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/134.txt
  fastlane/metadata/android/ru-RU/changelogs/136.txt
  fastlane/metadata/android/sv-SE/changelogs/134.txt
  fastlane/metadata/android/sv-SE/changelogs/136.txt
  fastlane/metadata/android/tr-TR/changelogs/134.txt
  fastlane/metadata/android/tr-TR/changelogs/136.txt
  fastlane/metadata/android/zh-CN/changelogs/136.txt
  fastlane/metadata/android/zh-TW/changelogs/134.txt
  fastlane/metadata/android/zh-TW/changelogs/136.txt
Labels: Releases
