Repository Automattic/simplenote-android, pull requests merged in 2021-03, with the labels that each got.

#1336 [Tooling] Mark *.enc configure files as binary
  .gitattributes
Labels: tooling

#1339 Add initial editorconfig setup
  .editorconfig
Labels: tooling

#1340 Sign Up Flow Update
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/DeepLinkActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/Simplenote.java
  Simplenote/src/main/java/com/automattic/simplenote/authentication/ConfirmationFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SignupFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SimplenoteAuthenticationActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SimplenoteCredentialsActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SimplenoteSignupActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/AuthUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/WordPressUtils.java
  Simplenote/src/main/res/drawable/ic_mail.xml
  Simplenote/src/main/res/layout/activity_signup.xml
  Simplenote/src/main/res/layout/fragment_confirmation.xml
  Simplenote/src/main/res/layout/fragment_signup.xml
  Simplenote/src/main/res/values/strings.xml
Labels: [status] needs design review, task

#1344 Merge 2.18 RC 1 into develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
  tools/extract_release_notes.rb
Labels: Releases

#1348 Merge finalized release 2.18 into develop
  README.md
  Simplenote/build.gradle
  Simplenote/src/main/res/values-sv/strings.xml
  fastlane/metadata/android/ar/changelogs/136.txt
  fastlane/metadata/android/ar/changelogs/138.txt
  fastlane/metadata/android/de-DE/changelogs/136.txt
  fastlane/metadata/android/de-DE/changelogs/138.txt
  fastlane/metadata/android/es-ES/changelogs/136.txt
  fastlane/metadata/android/es-ES/changelogs/138.txt
  fastlane/metadata/android/fr-FR/changelogs/136.txt
  fastlane/metadata/android/id/changelogs/136.txt
  fastlane/metadata/android/id/changelogs/138.txt
  fastlane/metadata/android/it-IT/changelogs/136.txt
  fastlane/metadata/android/it-IT/changelogs/138.txt
  fastlane/metadata/android/iw-IL/changelogs/136.txt
  fastlane/metadata/android/ja-JP/changelogs/136.txt
  fastlane/metadata/android/ko-KR/changelogs/136.txt
  fastlane/metadata/android/nl-NL/changelogs/136.txt
  fastlane/metadata/android/pt-BR/changelogs/136.txt
  fastlane/metadata/android/pt-BR/changelogs/138.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/136.txt
  fastlane/metadata/android/sv-SE/changelogs/136.txt
  fastlane/metadata/android/tr-TR/changelogs/136.txt
  fastlane/metadata/android/zh-CN/changelogs/136.txt
  fastlane/metadata/android/zh-CN/changelogs/138.txt
  fastlane/metadata/android/zh-TW/changelogs/136.txt
  fastlane/metadata/android/zh-TW/changelogs/138.txt
Labels: Releases
