Repository Automattic/simplenote-android, pull requests merged in 2021-07, with the labels that each got.

#1397 Add TagsViewModel to restructure UI and orchestration logic in TagsActivity
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/TagsActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/models/Note.java
  Simplenote/src/main/java/com/automattic/simplenote/models/TagItem.kt
  Simplenote/src/main/java/com/automattic/simplenote/repositories/SimperiumTagsRepository.kt
  Simplenote/src/main/java/com/automattic/simplenote/repositories/TagsRepository.kt
  Simplenote/src/main/java/com/automattic/simplenote/utils/TagItemAdapter.kt
  Simplenote/src/main/java/com/automattic/simplenote/utils/TagUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/TagsViewModel.kt
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/ViewModelFactory.kt
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/TagsViewModelTest.kt
Labels: debt, task

#1414 Fix list of searched tags after leaving and entering the app
  Simplenote/build.gradle
  Simplenote/src/androidTest/java/com/automattic/simplenote/integration/TagsActivityTest.kt
  Simplenote/src/androidTest/java/com/automattic/simplenote/utils/EspressoUtils.kt
  Simplenote/src/main/java/com/automattic/simplenote/TagsActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/TagsViewModel.kt
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/TagsViewModelTest.kt
Labels: [status] needs code review, bug

#1401 Check translation progress during final release
  Gemfile.lock
  fastlane/Fastfile
  fastlane/Pluginfile
Labels: tooling

#1333 Add import data
  Simplenote/src/main/java/com/automattic/simplenote/Importer.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/models/Note.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DateTimeUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/FileUtils.java
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/xml/preferences.xml
Labels: enhancement

#1418 Add final details to Import Data Feature
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/Importer.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/analytics/AnalyticsTracker.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/AppLog.java
Labels: [status] needs design review, task

#1416 Implements In App Account Deletion
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/analytics/AnalyticsTracker.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/AccountNetworkUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/AppLog.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/SimplenoteProgressDialogFragment.java
  Simplenote/src/main/res/layout/preference_red.xml
  Simplenote/src/main/res/layout/progressbar_dialog.xml
  Simplenote/src/main/res/values-night/colors.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/values/styles.xml
  Simplenote/src/main/res/xml/preferences.xml
Labels: enhancement, task
