Repository Automattic/simplenote-android, pull requests merged in 2021-09, with the labels that each got.

#1457 Fix editor's background color in landscape mode with dark theme
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/res/layout/fragment_note_editor.xml
Labels: [Type] Bug, [status] needs code review

#1470 Modify message shown to user when trying to delete account and when doesn't have connectivity
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/res/values/strings.xml
Labels: consistency, [Type] UX

#1471 Merge 2.20 final to develop
  Simplenote/build.gradle
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/140.txt
  fastlane/metadata/android/ar/changelogs/142.txt
  fastlane/metadata/android/de-DE/changelogs/140.txt
  fastlane/metadata/android/de-DE/changelogs/142.txt
  fastlane/metadata/android/es-ES/changelogs/140.txt
  fastlane/metadata/android/es-ES/changelogs/142.txt
  fastlane/metadata/android/fr-FR/changelogs/140.txt
  fastlane/metadata/android/fr-FR/changelogs/142.txt
  fastlane/metadata/android/id/changelogs/140.txt
  fastlane/metadata/android/id/changelogs/142.txt
  fastlane/metadata/android/it-IT/changelogs/140.txt
  fastlane/metadata/android/it-IT/changelogs/142.txt
  fastlane/metadata/android/iw-IL/changelogs/140.txt
  fastlane/metadata/android/iw-IL/changelogs/142.txt
  fastlane/metadata/android/ja-JP/changelogs/140.txt
  fastlane/metadata/android/ja-JP/changelogs/142.txt
  fastlane/metadata/android/ko-KR/changelogs/140.txt
  fastlane/metadata/android/ko-KR/changelogs/142.txt
  fastlane/metadata/android/nl-NL/changelogs/140.txt
  fastlane/metadata/android/nl-NL/changelogs/142.txt
  fastlane/metadata/android/pt-BR/changelogs/140.txt
  fastlane/metadata/android/pt-BR/changelogs/142.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/140.txt
  fastlane/metadata/android/ru-RU/changelogs/142.txt
  fastlane/metadata/android/sv-SE/changelogs/140.txt
  fastlane/metadata/android/sv-SE/changelogs/142.txt
  fastlane/metadata/android/tr-TR/changelogs/140.txt
  fastlane/metadata/android/tr-TR/changelogs/142.txt
  fastlane/metadata/android/zh-CN/changelogs/140.txt
  fastlane/metadata/android/zh-CN/changelogs/142.txt
  fastlane/metadata/android/zh-TW/changelogs/140.txt
  fastlane/metadata/android/zh-TW/changelogs/142.txt
Labels: Releases

#1467 Add check body for unverified accounts in 403 responses
  Simplenote/build.gradle
Labels: [Type] Enhancement, [status] needs code review

#1475 Merge 2.21 code freeze to develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
Labels: Releases

#1481 Refactor Tag Management in NoteEditorFragment
  Simplenote/build.gradle
  Simplenote/src/androidTest/java/com/automattic/simplenote/models/NoteTest.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/di/DataModule.kt
  Simplenote/src/main/java/com/automattic/simplenote/models/Note.java
  Simplenote/src/main/java/com/automattic/simplenote/repositories/CollaboratorsRepository.kt
  Simplenote/src/main/java/com/automattic/simplenote/repositories/SimperiumCollaboratorsRepository.kt
  Simplenote/src/main/java/com/automattic/simplenote/usecases/GetTagsUseCase.kt
  Simplenote/src/main/java/com/automattic/simplenote/usecases/ValidateTagUseCase.kt
  Simplenote/src/main/java/com/automattic/simplenote/utils/StrUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/NoteEditorViewModel.kt
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/test/java/com/automattic/simplenote/models/NoteTest.java
  Simplenote/src/test/java/com/automattic/simplenote/repositories/SimperiumCollaboratorsRepositoryTest.kt
  Simplenote/src/test/java/com/automattic/simplenote/usecases/GetTagsUseCaseTest.kt
  Simplenote/src/test/java/com/automattic/simplenote/usecases/ValidateTagUseCaseTest.kt
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/NoteEditorViewModelTest.kt
Labels: [Type] Enhancement, [status] needs code review, task, [Type] Debt, consistency

#1489 Do not assemble project when running tests on CI
  .circleci/config.yml
Labels: [Type] Enhancement, tooling

#1487 Integrate `Automattic-Tracks-Android 2.1.0`
  .configure
  .configure-files/sentry.properties.enc
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/Simplenote.java
  Simplenote/src/main/java/com/automattic/simplenote/di/AppModule.kt
  Simplenote/src/main/java/com/automattic/simplenote/di/DataModule.kt
  Simplenote/src/main/java/com/automattic/simplenote/utils/AuthUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/CrashUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/crashlogging/CrashLoggingModule.kt
  Simplenote/src/main/java/com/automattic/simplenote/utils/crashlogging/SimplenoteCrashLoggingDataProvider.kt
  Simplenote/src/main/java/com/automattic/simplenote/utils/locale/ContextBasedLocaleProvider.kt
  Simplenote/src/main/java/com/automattic/simplenote/utils/locale/LocaleProvider.kt
  gradle.properties
Labels: [Type] Debt, tooling

#1495 Fixes tag related bugs
  RELEASE-NOTES.txt
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/TagDialogFragment.kt
  Simplenote/src/main/res/layout/activity_tag_add.xml
  Simplenote/src/main/res/layout/edit_tag.xml
Labels: [Type] Bug, consistency

#1494 Update README
  README.md
Labels: [Type] Enhancement, consistency, documentation

#1497 Merge 2.21 final to develop
  Simplenote/build.gradle
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/metadata/android/ar/changelogs/142.txt
  fastlane/metadata/android/ar/changelogs/144.txt
  fastlane/metadata/android/de-DE/changelogs/142.txt
  fastlane/metadata/android/de-DE/changelogs/144.txt
  fastlane/metadata/android/es-ES/changelogs/142.txt
  fastlane/metadata/android/es-ES/changelogs/144.txt
  fastlane/metadata/android/fr-FR/changelogs/142.txt
  fastlane/metadata/android/fr-FR/changelogs/144.txt
  fastlane/metadata/android/id/changelogs/142.txt
  fastlane/metadata/android/id/changelogs/144.txt
  fastlane/metadata/android/it-IT/changelogs/142.txt
  fastlane/metadata/android/it-IT/changelogs/144.txt
  fastlane/metadata/android/iw-IL/changelogs/142.txt
  fastlane/metadata/android/iw-IL/changelogs/144.txt
  fastlane/metadata/android/ja-JP/changelogs/142.txt
  fastlane/metadata/android/ja-JP/changelogs/144.txt
  fastlane/metadata/android/ko-KR/changelogs/142.txt
  fastlane/metadata/android/ko-KR/changelogs/144.txt
  fastlane/metadata/android/nl-NL/changelogs/142.txt
  fastlane/metadata/android/nl-NL/changelogs/144.txt
  fastlane/metadata/android/pt-BR/changelogs/142.txt
  fastlane/metadata/android/pt-BR/changelogs/144.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/142.txt
  fastlane/metadata/android/ru-RU/changelogs/144.txt
  fastlane/metadata/android/sv-SE/changelogs/142.txt
  fastlane/metadata/android/sv-SE/changelogs/144.txt
  fastlane/metadata/android/tr-TR/changelogs/142.txt
  fastlane/metadata/android/tr-TR/changelogs/144.txt
  fastlane/metadata/android/zh-CN/changelogs/142.txt
  fastlane/metadata/android/zh-CN/changelogs/144.txt
  fastlane/metadata/android/zh-TW/changelogs/142.txt
  fastlane/metadata/android/zh-TW/changelogs/144.txt
Labels: Releases

#1500 Do not filter collaborators until we launch the UI for collaborators
  Simplenote/src/main/java/com/automattic/simplenote/usecases/GetTagsUseCase.kt
  Simplenote/src/test/java/com/automattic/simplenote/usecases/GetTagsUseCaseTest.kt
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/NoteEditorViewModelTest.kt
Labels: [status] needs code review, [priority] high, Part of a WIP Feature, [feature] tags

#1502 Merge 2.22 code freeze to develop
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
Labels: Releases

#1505 Add simperium strings to handle compromised passwords to Simplenote
  Simplenote/src/main/res/values/strings.xml
Labels: consistency, [Type] UX

#1491 Add collaboration UI
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/AddCollaboratorFragment.kt
  Simplenote/src/main/java/com/automattic/simplenote/CollaboratorsActivity.kt
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/TagDialogFragment.kt
  Simplenote/src/main/java/com/automattic/simplenote/analytics/AnalyticsTracker.java
  Simplenote/src/main/java/com/automattic/simplenote/di/ThreadModule.kt
  Simplenote/src/main/java/com/automattic/simplenote/repositories/CollaboratorsRepository.kt
  Simplenote/src/main/java/com/automattic/simplenote/repositories/SimperiumCollaboratorsRepository.kt
  Simplenote/src/main/java/com/automattic/simplenote/repositories/SimperiumTagsRepository.kt
  Simplenote/src/main/java/com/automattic/simplenote/utils/CollaboratorsAdapter.kt
  Simplenote/src/main/java/com/automattic/simplenote/utils/Either.kt
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/AddCollaboratorViewModel.kt
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/CollaboratorsViewModel.kt
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/NoteEditorViewModel.kt
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/ViewModelFactory.kt
  Simplenote/src/main/res/layout/activity_collaborators.xml
  Simplenote/src/main/res/layout/activity_tags.xml
  Simplenote/src/main/res/layout/add_collaborator.xml
  Simplenote/src/main/res/layout/collaborator_row.xml
  Simplenote/src/main/res/menu/note_editor.xml
  Simplenote/src/main/res/menu/notes_list.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/test/java/com/automattic/simplenote/repositories/SimperiumCollaboratorsRepositoryTest.kt
  Simplenote/src/test/java/com/automattic/simplenote/usecases/GetTagsUseCaseTest.kt
  Simplenote/src/test/java/com/automattic/simplenote/usecases/ValidateTagUseCaseTest.kt
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/AddCollaboratorViewModelTest.kt
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/AddTagViewModelTest.kt
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/CollaboratorsViewModelTest.kt
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/NoteEditorViewModelTest.kt
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/TagDialogViewModelTest.kt
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/TagsViewModelTest.kt
Labels: [Type] Enhancement, [status] needs code review, [status] needs design review, consistency, [feature] tags

#1499 Add "note shared" indicator to notes in the notes list
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/models/Note.java
  Simplenote/src/main/java/com/automattic/simplenote/repositories/SimperiumCollaboratorsRepository.kt
  Simplenote/src/main/java/com/automattic/simplenote/utils/StrUtils.java
  Simplenote/src/main/res/drawable/ic_collaborate_16dp.xml
  Simplenote/src/main/res/layout/note_list_row.xml
  Simplenote/src/main/res/values/strings.xml
Labels: [Type] Enhancement, consistency, [Type] UX

#1504 Avoid hiding/showing toolbar when note reference is null
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
Labels: [Type] Bug, crash

#1509 Refactor tag screens to filter out collaborators
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/usecases/GetTagsUseCase.kt
  Simplenote/src/main/java/com/automattic/simplenote/utils/TagsAdapter.java
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/AddTagViewModel.kt
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/TagDialogViewModel.kt
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/TagsViewModel.kt
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/test/java/com/automattic/simplenote/usecases/GetTagsUseCaseTest.kt
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/AddTagViewModelTest.kt
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/NoteEditorViewModelTest.kt
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/TagDialogViewModelTest.kt
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/TagsViewModelTest.kt
Labels: [Type] Enhancement, [status] needs code review, task, consistency

#1510 Improvements to collaboration UI
  Simplenote/src/main/java/com/automattic/simplenote/AddCollaboratorFragment.kt
  Simplenote/src/main/java/com/automattic/simplenote/CollaboratorsActivity.kt
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SessionManager.kt
  Simplenote/src/main/java/com/automattic/simplenote/di/DataModule.kt
  Simplenote/src/main/java/com/automattic/simplenote/utils/CollaboratorsAdapter.kt
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/AddCollaboratorViewModel.kt
  Simplenote/src/main/res/layout/activity_collaborators.xml
  Simplenote/src/main/res/layout/activity_tags.xml
  Simplenote/src/main/res/layout/collaborator_row.xml
  Simplenote/src/main/res/layout/collaborators_header.xml
  Simplenote/src/main/res/layout/empty_view_message.xml
  Simplenote/src/main/res/menu/note_markdown.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/test/java/com/automattic/simplenote/authentication/SessionManagerTest.kt
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/AddCollaboratorViewModelTest.kt
Labels: [status] needs code review, task, [Type] UX

#1512 Fix case in delete account button in settings
  RELEASE-NOTES.txt
  Simplenote/src/main/res/values/strings.xml
Labels: consistency, [Type] UX

#1514 Update error handling in login to handle 429 response (too many wrong credentials at login)
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SimplenoteCredentialsActivity.java
  Simplenote/src/main/res/values/strings.xml
Labels: [Type] Enhancement, consistency
