Repository Automattic/simplenote-android, pull requests merged in 2022-11, with the labels that each got.

#1567 Add Sustainer Banner and IAP flow
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/Simplenote.java
  Simplenote/src/main/java/com/automattic/simplenote/billing/SubscriptionBottomSheetDialog.kt
  Simplenote/src/main/java/com/automattic/simplenote/billing/SubscriptionDurationAdapter.kt
  Simplenote/src/main/java/com/automattic/simplenote/utils/PrefUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/IapViewModel.kt
  Simplenote/src/main/res/drawable/bg_bottom_sheet_handle.xml
  Simplenote/src/main/res/drawable/bg_iap_banner.xml
  Simplenote/src/main/res/drawable/bg_iap_thank_you_banner.xml
  Simplenote/src/main/res/layout/activity_notes.xml
  Simplenote/src/main/res/layout/activity_preferences.xml
  Simplenote/src/main/res/layout/bottom_sheet_subscriptions.xml
  Simplenote/src/main/res/layout/iap_banner.xml
  Simplenote/src/main/res/layout/iap_thank_you_banner.xml
  Simplenote/src/main/res/layout/subscription_duration_list_row.xml
  Simplenote/src/main/res/values/dimens.xml
  Simplenote/src/main/res/values/strings.xml
Labels: task

#1569 Add cross platform IAP status sync and tracking.
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/analytics/AnalyticsTracker.java
  Simplenote/src/main/java/com/automattic/simplenote/billing/SubscriptionBottomSheetDialog.kt
  Simplenote/src/main/java/com/automattic/simplenote/billing/SubscriptionDurationAdapter.kt
  Simplenote/src/main/java/com/automattic/simplenote/models/Preferences.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/PrefUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/IapViewModel.kt
Labels: task

#1571 Upgrade tagetSdkVersion to Android 31
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/NoteListWidgetDark.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListWidgetLight.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetDark.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetDarkConfigureActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetLight.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetLightConfigureActivity.java
Labels: [priority] high, task, [Type] Debt

#1573 Merge 2.25 code freeze into trunk
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
Labels: Releases

#1574 `Gradle Wrapper Validation
  .buildkite/pipeline.yml
  .github/workflows/gradle-wrapper-validation.yml
Labels: tooling
