Repository Automattic/simplenote-android, pull requests merged in 2023-08, with the labels that each got.

#1601 Added a catch for billing exception on samsung devices.
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/IapViewModel.kt
Labels: crash

#1604 Merge 2.28 final to trunk
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  fastlane/Fastfile
  fastlane/metadata/android/ar/changelogs/157.txt
  fastlane/metadata/android/de-DE/changelogs/157.txt
  fastlane/metadata/android/es-ES/changelogs/157.txt
  fastlane/metadata/android/fr-FR/changelogs/157.txt
  fastlane/metadata/android/id/changelogs/157.txt
  fastlane/metadata/android/it-IT/changelogs/157.txt
  fastlane/metadata/android/iw-IL/changelogs/157.txt
  fastlane/metadata/android/ja-JP/changelogs/157.txt
  fastlane/metadata/android/ko-KR/changelogs/157.txt
  fastlane/metadata/android/nl-NL/changelogs/157.txt
  fastlane/metadata/android/pt-BR/changelogs/157.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/157.txt
  fastlane/metadata/android/sv-SE/changelogs/157.txt
  fastlane/metadata/android/tr-TR/changelogs/157.txt
  fastlane/metadata/android/zh-CN/changelogs/157.txt
  fastlane/metadata/android/zh-TW/changelogs/157.txt
Labels: Releases

#1605 Fix crash when visiting preference activity
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesActivity.java
Labels: [Type] Bug

#1606 Merge 2.29 final to trunk
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  fastlane/metadata/android/release_notes.xml
Labels: Releases
