Repository Automattic/simplenote-android, pull requests merged in 2024-07, with the labels that each got.

#1660 [Authentication] Add logic to login via magic link
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/DeepLinkActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/DeepLinkActivity.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/ConfirmationFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/authentication/MagicLinkableFragment.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SignInFragment.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SignupFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SimplenoteAuthenticationActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SimplenoteSignupActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/authentication/magiclink/OkHttpMagicLinkRepository.kt
  Simplenote/src/main/java/com/automattic/simplenote/di/DataModule.kt
  Simplenote/src/main/java/com/automattic/simplenote/di/NetworkModule.kt
  Simplenote/src/main/java/com/automattic/simplenote/networking/SimpleHttp.kt
  Simplenote/src/main/java/com/automattic/simplenote/repositories/MagicLinkRepository.kt
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/CompleteMagicLinkViewModel.kt
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/RequestMagicLinkViewModel.kt
  Simplenote/src/main/res/layout/activity_signup.xml
  Simplenote/src/main/res/layout/fragment_login.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/CompleteMagicLinkViewModelTest.kt
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/RequestMagicLinkViewModelTest.kt
Labels: [Type] Enhancement, unit-tests-exemption

#1662 [Buildkite] Add Agent Attribute with Queue Android to Every YML File
  .buildkite/pipeline.yml
Labels: tooling

#1663 [Analytics] Add trackers for magic link sign in.
  Simplenote/src/main/java/com/automattic/simplenote/analytics/AnalyticsTracker.java
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SignInFragment.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SimplenoteAuthenticationActivity.java
Labels: analytics

#1666 [Bug] Entering email in magic link screen shows it in login with pass.
  Simplenote/src/main/java/com/automattic/simplenote/authentication/MagicLinkableFragment.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SignInFragment.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SimplenoteCredentialsActivity.java
Labels: [Type] Enhancement

#1665 [Auth] Ability to add Passkeys to your account.
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/authentication/MagicLinkableFragment.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SignInFragment.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SimplenoteCredentialsActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/authentication/passkey/OkHttpPasskeyRepository.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/passkey/PasskeyManager.kt
  Simplenote/src/main/java/com/automattic/simplenote/di/DataModule.kt
  Simplenote/src/main/java/com/automattic/simplenote/networking/OkHttpEndpoints.kt
  Simplenote/src/main/java/com/automattic/simplenote/networking/SimpleHttp.kt
  Simplenote/src/main/java/com/automattic/simplenote/repositories/PasskeyRepository.kt
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/PasskeyViewModel.kt
  Simplenote/src/main/res/layout/passkey_add_dialog.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/xml/preferences.xml
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/PasskeyViewModelTest.kt
Labels: [Type] Enhancement, unit-tests-exemption
