Repository Automattic/simplenote-android, pull requests merged in 2024-04, with the labels that each got.

#1644 Remove sustainer UI
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/NotesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/analytics/AnalyticsTracker.java
  Simplenote/src/main/java/com/automattic/simplenote/billing/SubscriptionBottomSheetDialog.kt
  Simplenote/src/main/java/com/automattic/simplenote/billing/SubscriptionDurationAdapter.kt
  Simplenote/src/main/java/com/automattic/simplenote/models/Preferences.java
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/IapViewModel.kt
  Simplenote/src/main/res/drawable/bg_iap_banner.xml
  Simplenote/src/main/res/drawable/bg_iap_thank_you_banner.xml
  Simplenote/src/main/res/layout/activity_notes.xml
  Simplenote/src/main/res/layout/activity_preferences.xml
  Simplenote/src/main/res/layout/bottom_sheet_subscriptions.xml
  Simplenote/src/main/res/layout/iap_banner.xml
  Simplenote/src/main/res/layout/iap_thank_you_banner.xml
  Simplenote/src/main/res/values/strings.xml
Labels: task

#1645 Add custom icon preference for sustainers
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/CollaboratorsActivity.kt
  Simplenote/src/main/java/com/automattic/simplenote/DeepLinkActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListWidgetDark.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListWidgetLight.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetDark.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteWidgetLight.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/IntentUtils.java
  Simplenote/src/main/res/drawable/ic_launcher_foreground_green.xml
  Simplenote/src/main/res/mipmap-anydpi-v26/ic_launcher_green.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/main/res/xml/preferences.xml
Labels: [Type] Enhancement

#1646 Add check for was_sustainer property to verify sustainer status
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/models/Preferences.java
Labels: task

#1647 Add a check for was_sustainer property to be an int.
  Simplenote/src/main/java/com/automattic/simplenote/models/Preferences.java
Labels: task

#1651 Merge 2.32-rc-1 into trunk
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/metadata/release_notes.txt
  fastlane/resources/values/strings.xml
Labels: Releases

#1653 Merge 2.32 final into trunk
  Simplenote/build.gradle
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/Fastfile
  fastlane/metadata/android/ar/changelogs/164.txt
  fastlane/metadata/android/ar/changelogs/166.txt
  fastlane/metadata/android/de-DE/changelogs/164.txt
  fastlane/metadata/android/de-DE/changelogs/166.txt
  fastlane/metadata/android/es-ES/changelogs/164.txt
  fastlane/metadata/android/es-ES/changelogs/166.txt
  fastlane/metadata/android/fr-FR/changelogs/164.txt
  fastlane/metadata/android/fr-FR/changelogs/166.txt
  fastlane/metadata/android/id/changelogs/164.txt
  fastlane/metadata/android/id/changelogs/166.txt
  fastlane/metadata/android/it-IT/changelogs/164.txt
  fastlane/metadata/android/it-IT/changelogs/166.txt
  fastlane/metadata/android/iw-IL/changelogs/164.txt
  fastlane/metadata/android/ja-JP/changelogs/164.txt
  fastlane/metadata/android/ja-JP/changelogs/166.txt
  fastlane/metadata/android/ko-KR/changelogs/164.txt
  fastlane/metadata/android/ko-KR/changelogs/166.txt
  fastlane/metadata/android/nl-NL/changelogs/164.txt
  fastlane/metadata/android/nl-NL/changelogs/166.txt
  fastlane/metadata/android/pt-BR/changelogs/164.txt
  fastlane/metadata/android/pt-BR/changelogs/166.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/164.txt
  fastlane/metadata/android/sv-SE/changelogs/164.txt
  fastlane/metadata/android/sv-SE/changelogs/166.txt
  fastlane/metadata/android/tr-TR/changelogs/164.txt
  fastlane/metadata/android/tr-TR/changelogs/166.txt
  fastlane/metadata/android/zh-CN/changelogs/164.txt
  fastlane/metadata/android/zh-CN/changelogs/166.txt
  fastlane/metadata/android/zh-TW/changelogs/164.txt
  fastlane/metadata/android/zh-TW/changelogs/166.txt
Labels: Releases

#1652 Add notice banner about collaboration removal.
  Simplenote/src/main/java/com/automattic/simplenote/CollaboratorsActivity.kt
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/CollaboratorsViewModel.kt
  Simplenote/src/main/res/drawable/bg_banner.xml
  Simplenote/src/main/res/layout/activity_collaborators.xml
  Simplenote/src/main/res/values/strings.xml
Labels: task
