Repository Automattic/simplenote-android, pull requests merged in 2024-09, with the labels that each got.

#1687 Merge release/2.33 into trunk
  Gemfile
  Gemfile.lock
  RELEASE-NOTES.txt
  Simplenote/build.gradle
  Simplenote/src/main/res/values-ar/strings.xml
  Simplenote/src/main/res/values-de/strings.xml
  Simplenote/src/main/res/values-es/strings.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-he/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-ko/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  fastlane/Fastfile
  fastlane/metadata/android/ar/changelogs/166.txt
  fastlane/metadata/android/ar/changelogs/169.txt
  fastlane/metadata/android/de-DE/changelogs/166.txt
  fastlane/metadata/android/de-DE/changelogs/169.txt
  fastlane/metadata/android/es-ES/changelogs/166.txt
  fastlane/metadata/android/es-ES/changelogs/169.txt
  fastlane/metadata/android/fr-FR/changelogs/166.txt
  fastlane/metadata/android/fr-FR/changelogs/169.txt
  fastlane/metadata/android/id/changelogs/166.txt
  fastlane/metadata/android/id/changelogs/169.txt
  fastlane/metadata/android/it-IT/changelogs/166.txt
  fastlane/metadata/android/it-IT/changelogs/169.txt
  fastlane/metadata/android/iw-IL/changelogs/169.txt
  fastlane/metadata/android/ja-JP/changelogs/166.txt
  fastlane/metadata/android/ja-JP/changelogs/169.txt
  fastlane/metadata/android/ko-KR/changelogs/166.txt
  fastlane/metadata/android/ko-KR/changelogs/169.txt
  fastlane/metadata/android/nl-NL/changelogs/166.txt
  fastlane/metadata/android/nl-NL/changelogs/169.txt
  fastlane/metadata/android/pt-BR/changelogs/166.txt
  fastlane/metadata/android/pt-BR/changelogs/169.txt
  fastlane/metadata/android/release_notes.xml
  fastlane/metadata/android/ru-RU/changelogs/169.txt
  fastlane/metadata/android/sv-SE/changelogs/166.txt
  fastlane/metadata/android/sv-SE/changelogs/169.txt
  fastlane/metadata/android/tr-TR/changelogs/166.txt
  fastlane/metadata/android/tr-TR/changelogs/169.txt
  fastlane/metadata/android/zh-CN/changelogs/166.txt
  fastlane/metadata/android/zh-CN/changelogs/169.txt
  fastlane/metadata/android/zh-TW/changelogs/166.txt
  fastlane/metadata/android/zh-TW/changelogs/169.txt
  version.properties
Labels: Releases

#1688 Add automation to run code freeze in CI
  .buildkite/commands/checkout-release-branch.sh
  .buildkite/commands/release-build.sh
  .buildkite/commands/release-create-on-github.sh
  .buildkite/commands/release-upload.sh
  .buildkite/pipeline.yml
  .buildkite/release-build.yml
  .buildkite/release-pipelines/complete-code-freeze.yml
  .buildkite/release-pipelines/start-code-freeze.yml
  .buildkite/shared-pipeline-vars
  .rubocop.yml
  Gemfile
  Gemfile.lock
  fastlane/Fastfile
  fastlane/lanes/build.rb
  fastlane/lanes/ci_releases.rb
  fastlane/lanes/localization.rb
  fastlane/lanes/release.rb
  fastlane/metadata/android/ar/changelogs/.gitkeep
  fastlane/metadata/android/ar/changelogs/169.txt
  fastlane/metadata/android/de-DE/changelogs/.gitkeep
  fastlane/metadata/android/de-DE/changelogs/169.txt
  fastlane/metadata/android/en-US/changelogs/.gitkeep
  fastlane/metadata/android/en-US/full_description.txt
  fastlane/metadata/android/en-US/release_notes.txt
  fastlane/metadata/android/en-US/short_description.txt
  fastlane/metadata/android/en-US/title.txt
  fastlane/metadata/android/es-ES/changelogs/.gitkeep
  fastlane/metadata/android/es-ES/changelogs/169.txt
  fastlane/metadata/android/fr-FR/changelogs/.gitkeep
  fastlane/metadata/android/fr-FR/changelogs/169.txt
  fastlane/metadata/android/id/changelogs/.gitkeep
  fastlane/metadata/android/id/changelogs/169.txt
  fastlane/metadata/android/it-IT/changelogs/.gitkeep
  fastlane/metadata/android/it-IT/changelogs/169.txt
  fastlane/metadata/android/iw-IL/changelogs/.gitkeep
  fastlane/metadata/android/iw-IL/changelogs/169.txt
  fastlane/metadata/android/ja-JP/changelogs/.gitkeep
  fastlane/metadata/android/ja-JP/changelogs/169.txt
  fastlane/metadata/android/ko-KR/changelogs/.gitkeep
  fastlane/metadata/android/ko-KR/changelogs/169.txt
  fastlane/metadata/android/nl-NL/changelogs/.gitkeep
  fastlane/metadata/android/nl-NL/changelogs/169.txt
  fastlane/metadata/android/pt-BR/changelogs/.gitkeep
  fastlane/metadata/android/pt-BR/changelogs/169.txt
  fastlane/metadata/android/ru-RU/changelogs/.gitkeep
  fastlane/metadata/android/ru-RU/changelogs/169.txt
  fastlane/metadata/android/sv-SE/changelogs/.gitkeep
  fastlane/metadata/android/sv-SE/changelogs/169.txt
  fastlane/metadata/android/tr-TR/changelogs/.gitkeep
  fastlane/metadata/android/tr-TR/changelogs/169.txt
  fastlane/metadata/android/zh-CN/changelogs/.gitkeep
  fastlane/metadata/android/zh-CN/changelogs/169.txt
  fastlane/metadata/android/zh-TW/changelogs/.gitkeep
  fastlane/metadata/android/zh-TW/changelogs/169.txt
Labels: tooling

#1691 Update release notes source with placeholder copy for 2.34
  fastlane/metadata/android/en-US/changelogs/default.txt
Labels: Releases

#1673 [Bug] If a deeplink is malformed or missing data we show auth screen.
  Simplenote/src/main/java/com/automattic/simplenote/DeepLinkActivity.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SimplenoteAuthenticationActivity.java
Labels: [Type] Bug

#1692 Merge 2.34 code freeze
  .buildkite/commands/build-prototype.sh
  .buildkite/commands/checkout-release-branch.sh
  .buildkite/commands/release-build.sh
  .buildkite/commands/release-create-on-github.sh
  .buildkite/commands/release-upload.sh
  .configure
  .configure-files/automattic.jks.enc
  .configure-files/debug.keystore.enc
  .configure-files/google-upload-credentials.json.enc
  .configure-files/gradle.properties.enc
  .configure-files/sentry.properties.enc
  RELEASE-NOTES.txt
  Simplenote/metadata/PlayStoreStrings.pot
  Simplenote/src/main/java/com/automattic/simplenote/DeepLinkActivity.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SimplenoteAuthenticationActivity.java
  fastlane/Fastfile
  fastlane/lanes/build.rb
  fastlane/lanes/release.rb
  fastlane/metadata/android/en-US/changelogs/default.txt
  fastlane/resources/values/strings.xml
  version.properties
Labels: Releases

#1694 Update California privacy policy link
  RELEASE-NOTES.txt
  Simplenote/src/main/java/com/automattic/simplenote/AboutFragment.java
Labels: [status] needs code review, Releases

#1693 Add message to allow user to login manually in the enter email screen.
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SignInFragment.kt
  Simplenote/src/main/res/layout/fragment_login.xml
  Simplenote/src/main/res/values/strings.xml
Labels: task

#1695 Merge release 2.34 into `trunk`
  .buildkite/release-pipelines/finalize-release.yml
  .buildkite/release-pipelines/publish-release.yml
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SignInFragment.kt
  Simplenote/src/main/res/layout/fragment_login.xml
  Simplenote/src/main/res/values-fr/strings.xml
  Simplenote/src/main/res/values-id/strings.xml
  Simplenote/src/main/res/values-it/strings.xml
  Simplenote/src/main/res/values-ja/strings.xml
  Simplenote/src/main/res/values-nl/strings.xml
  Simplenote/src/main/res/values-pt-rBR/strings.xml
  Simplenote/src/main/res/values-ru/strings.xml
  Simplenote/src/main/res/values-sv/strings.xml
  Simplenote/src/main/res/values-tr/strings.xml
  Simplenote/src/main/res/values-zh-rCN/strings.xml
  Simplenote/src/main/res/values-zh-rTW/strings.xml
  Simplenote/src/main/res/values/strings.xml
  fastlane/Fastfile
  fastlane/lanes/build.rb
  fastlane/lanes/ci_releases.rb
  fastlane/lanes/release.rb
  fastlane/metadata/android/fr-FR/changelogs/default.txt
  fastlane/metadata/android/id/changelogs/default.txt
  fastlane/metadata/android/it-IT/changelogs/default.txt
  fastlane/metadata/android/ja-JP/changelogs/default.txt
  fastlane/metadata/android/nl-NL/changelogs/default.txt
  fastlane/metadata/android/pt-BR/changelogs/default.txt
  fastlane/metadata/android/ru-RU/changelogs/default.txt
  fastlane/metadata/android/sv-SE/changelogs/default.txt
  fastlane/metadata/android/tr-TR/changelogs/default.txt
  fastlane/metadata/android/zh-CN/changelogs/default.txt
  fastlane/metadata/android/zh-TW/changelogs/default.txt
  version.properties
Labels: Releases

#1698 Extract create backmerge PR methods in helper files
  fastlane/Fastfile
  fastlane/lanes/release.rb
  fastlane/lib/release_helpers.rb
Labels: tooling
