Repository Automattic/simplenote-android, pull requests merged in 2024-08, with the labels that each got.

#1674 Update strings for translation - version 2.33
  Simplenote/metadata/PlayStoreStrings.pot
  fastlane/Fastfile
Labels: Releases

#1672 Go back one screen when confirming a code response says it expired.
  Simplenote/src/main/java/com/automattic/simplenote/authentication/magiclink/MagicLinkAuthError.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/magiclink/MagicLinkConfirmationFragment.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/magiclink/OkHttpMagicLinkRepository.kt
  Simplenote/src/main/java/com/automattic/simplenote/repositories/MagicLinkRepository.kt
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/CompleteMagicLinkViewModel.kt
Labels: task, unit-tests-exemption

#1677 [Tooling] Update Ruby Dependencies
  Gemfile.lock
Labels: tooling, dependencies

#1678 [Lib] Migrate passcodelock directly into simplenote as a library module.
  PasscodeLock/.gitignore
  PasscodeLock/build.gradle
  PasscodeLock/consumer-rules.pro
  PasscodeLock/gradle.properties
  PasscodeLock/proguard-rules.pro
  PasscodeLock/src/main/AndroidManifest.xml
  PasscodeLock/src/main/java/org/wordpress/passcodelock/AbstractAppLock.java
  PasscodeLock/src/main/java/org/wordpress/passcodelock/AbstractPasscodeKeyboardActivity.java
  PasscodeLock/src/main/java/org/wordpress/passcodelock/AppLockManager.java
  PasscodeLock/src/main/java/org/wordpress/passcodelock/DefaultAppLock.java
  PasscodeLock/src/main/java/org/wordpress/passcodelock/PasscodeManagePasswordActivity.java
  PasscodeLock/src/main/java/org/wordpress/passcodelock/PasscodePreferenceFragment.java
  PasscodeLock/src/main/java/org/wordpress/passcodelock/PasscodePreferenceFragmentCompat.java
  PasscodeLock/src/main/java/org/wordpress/passcodelock/PasscodeUnlockActivity.java
  PasscodeLock/src/main/java/org/wordpress/passcodelock/StringUtils.java
  PasscodeLock/src/main/res/anim/cycle_5.xml
  PasscodeLock/src/main/res/anim/do_nothing.xml
  PasscodeLock/src/main/res/anim/shake.xml
  PasscodeLock/src/main/res/anim/slide_up.xml
  PasscodeLock/src/main/res/drawable-hdpi/ic_backspace_white_24dp.png
  PasscodeLock/src/main/res/drawable-hdpi/ic_fingerprint_white_24dp.png
  PasscodeLock/src/main/res/drawable-mdpi/ic_backspace_white_24dp.png
  PasscodeLock/src/main/res/drawable-mdpi/ic_fingerprint_white_24dp.png
  PasscodeLock/src/main/res/drawable-xhdpi/ic_backspace_white_24dp.png
  PasscodeLock/src/main/res/drawable-xhdpi/ic_fingerprint_white_24dp.png
  PasscodeLock/src/main/res/drawable-xxhdpi/ic_backspace_white_24dp.png
  PasscodeLock/src/main/res/drawable-xxhdpi/ic_fingerprint_white_24dp.png
  PasscodeLock/src/main/res/drawable-xxxhdpi/ic_backspace_white_24dp.png
  PasscodeLock/src/main/res/drawable-xxxhdpi/ic_fingerprint_white_24dp.png
  PasscodeLock/src/main/res/layout-sw600dp/app_passcode_keyboard.xml
  PasscodeLock/src/main/res/layout/app_passcode_keyboard.xml
  PasscodeLock/src/main/res/values-sw600dp/bools.xml
  PasscodeLock/src/main/res/values-xlarge/bools.xml
  PasscodeLock/src/main/res/values/bools.xml
  PasscodeLock/src/main/res/values/colors.xml
  PasscodeLock/src/main/res/values/dimens.xml
  PasscodeLock/src/main/res/values/strings.xml
  PasscodeLock/src/main/res/values/styles.xml
  PasscodeLock/src/main/res/xml/passcode_preferences.xml
  Simplenote/build.gradle
  build.gradle
  settings.gradle
Labels: task, unit-tests-exemption

#1675 [Auth] Added Accept-Language header for localizing magic link email.
  Simplenote/src/main/java/com/automattic/simplenote/di/NetworkModule.kt
  Simplenote/src/main/java/com/automattic/simplenote/networking/HeadersInterceptor.kt
Labels: task, unit-tests-exemption

#1671 [Auth] Copied over CredentialsActivity from Simperium to customize login screen.
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/authentication/NewCredentialsActivity.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SignInFragment.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SimplenoteCredentialsActivity.java
  Simplenote/src/main/res/layout/new_activity_credentials.xml
  Simplenote/src/main/res/values/strings.xml
Labels: task

#1680 Update release-toolkit and Fastlane automation to modern setup
  Gemfile
  Gemfile.lock
  Simplenote/build.gradle
  Simplenote/metadata/PlayStoreStrings.pot
  fastlane/Fastfile
  version.properties
Labels: Releases

#1667 [Auth] Add ability to login with a passkey.
  Simplenote/src/main/java/com/automattic/simplenote/DeepLinkActivity.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/BaseAuthenticationFragment.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SignInFragment.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/magiclink/MagicLinkConfirmationFragment.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/passkey/OkHttpPasskeyRepository.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/passkey/PasskeyManager.kt
  Simplenote/src/main/java/com/automattic/simplenote/networking/OkHttpEndpoints.kt
  Simplenote/src/main/java/com/automattic/simplenote/networking/SimpleHttp.kt
  Simplenote/src/main/java/com/automattic/simplenote/repositories/PasskeyRepository.kt
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/CompleteMagicLinkViewModel.kt
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/PasskeyViewModel.kt
  Simplenote/src/main/java/com/automattic/simplenote/viewmodels/RequestMagicLinkViewModel.kt
  Simplenote/src/main/res/layout/fragment_login.xml
  Simplenote/src/main/res/values/strings.xml
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/PasskeyViewModelTest.kt
Labels: [Type] Enhancement

#1686 [Tooling] Run Danger on Buildkite Linter Agent
  .buildkite/pipeline.yml
  .github/workflows/run-danger.yml
  Gemfile.lock
Labels: tooling

#1685 [Lib] Update simperium-android to fix ssl cert bug.
  RELEASE-NOTES.txt
  Simplenote/build.gradle
Labels: [Type] Bug
