Repository Automattic/simplenote-android, pull requests merged in 2025-08, with the labels that each got.

#1733 Update libraries and fix crashes
  .buildkite/pipeline.yml
  .java-version
  PasscodeLock/build.gradle
  PasscodeLock/consumer-rules.pro
  PasscodeLock/src/main/java/org/wordpress/passcodelock/AbstractPasscodeKeyboardActivity.java
  PasscodeLock/src/main/java/org/wordpress/passcodelock/PasscodeManagePasswordActivity.java
  PasscodeLock/src/main/java/org/wordpress/passcodelock/PasscodeUnlockActivity.java
  Simplenote/build.gradle
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/DeepLinkActivity.kt
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/authentication/NewCredentialsActivity.kt
  Simplenote/src/main/java/com/automattic/simplenote/widgets/SimplenoteEditText.java
  Simplenote/src/main/res/layout-large-land/fragment_note_editor.xml
  Simplenote/src/main/res/layout/activity_note_editor.xml
  Simplenote/src/main/res/layout/collaborator_row.xml
  Simplenote/src/main/res/layout/empty_view.xml
  Simplenote/src/main/res/layout/empty_view_message.xml
  Simplenote/src/main/res/layout/fragment_note_editor.xml
  Simplenote/src/main/res/layout/fragment_note_error.xml
  Simplenote/src/main/res/layout/fragment_review_account_verify_email.xml
  Simplenote/src/main/res/layout/note_list_row.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_black.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_classic.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_default.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_matrix.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_mono.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_publication.xml
  Simplenote/src/main/res/layout/note_list_widget_dark_sepia.xml
  Simplenote/src/main/res/layout/note_list_widget_item_dark.xml
  Simplenote/src/main/res/layout/note_list_widget_item_dark_monospace.xml
  Simplenote/src/main/res/layout/note_list_widget_item_dark_serif.xml
  Simplenote/src/main/res/layout/note_list_widget_item_light.xml
  Simplenote/src/main/res/layout/note_list_widget_item_light_monospace.xml
  Simplenote/src/main/res/layout/note_list_widget_item_light_serif.xml
  Simplenote/src/main/res/layout/note_list_widget_light_black.xml
  Simplenote/src/main/res/layout/note_list_widget_light_classic.xml
  Simplenote/src/main/res/layout/note_list_widget_light_default.xml
  Simplenote/src/main/res/layout/note_list_widget_light_matrix.xml
  Simplenote/src/main/res/layout/note_list_widget_light_mono.xml
  Simplenote/src/main/res/layout/note_list_widget_light_publication.xml
  Simplenote/src/main/res/layout/note_list_widget_light_sepia.xml
  Simplenote/src/main/res/layout/search_suggestion.xml
  Simplenote/src/main/res/layout/style_list_row_black.xml
  Simplenote/src/main/res/layout/style_list_row_default.xml
  Simplenote/src/main/res/layout/style_list_row_matrix.xml
  Simplenote/src/main/res/layout/style_list_row_mono.xml
  Simplenote/src/main/res/layout/style_list_row_publication.xml
  Simplenote/src/main/res/layout/style_list_row_sepia.xml
  Simplenote/src/main/res/layout/tags_list_row.xml
  Simplenote/src/main/res/values/styles.xml
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/CollaboratorsViewModelTest.kt
  Simplenote/src/test/java/com/automattic/simplenote/viewmodels/TagDialogViewModelTest.kt
  Wear/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: [Type] Debt, dependencies, Core

#1737 Update part 2: updating for Android 15 (sdk 35) compatibility
  PasscodeLock/src/main/java/org/wordpress/passcodelock/PasscodeManagePasswordActivity.java
  PasscodeLock/src/main/res/layout/app_passcode_keyboard.xml
  Simplenote/build.gradle
  Simplenote/src/main/AndroidManifest.xml
  Simplenote/src/main/java/com/automattic/simplenote/AboutActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/AddTagActivity.kt
  Simplenote/src/main/java/com/automattic/simplenote/CollaboratorsActivity.kt
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteEditorFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteListFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/PreferencesActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/TagsActivity.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SimplenoteAuthenticationActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SimplenoteSignupActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/DisplayUtils.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/SystemBarUtils.kt
  Simplenote/src/main/res/layout/activity_about.xml
  Simplenote/src/main/res/layout/activity_collaborators.xml
  Simplenote/src/main/res/layout/activity_note_editor.xml
  Simplenote/src/main/res/layout/activity_preferences.xml
  Simplenote/src/main/res/layout/activity_signup.xml
  Simplenote/src/main/res/layout/activity_tag_add.xml
  Simplenote/src/main/res/layout/activity_tags.xml
  Simplenote/src/main/res/layout/fragment_login.xml
  Simplenote/src/main/res/layout/fragment_magic_link_code.xml
  Simplenote/src/main/res/layout/fragment_signup.xml
  Simplenote/src/main/res/layout/toolbar.xml
  Simplenote/src/main/res/values-night-v35/styles.xml
  Simplenote/src/main/res/values-v35/styles.xml
  Wear/build.gradle
Labels: [Type] Debt, unit-tests-exemption

#1738 Replaced markdown library `com.commonsware.cwac:anddown` with jetbrains' markdown for html conversions
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.java
  Simplenote/src/main/java/com/automattic/simplenote/NoteMarkdownFragment.kt
  Simplenote/src/main/java/com/automattic/simplenote/utils/markdown/SimplenoteMarkdownFlavorDescriptor.kt
Labels: [Type] Debt, unit-tests-exemption

#1743 targetSdk 35: sign up & login dark mode support fixes
  Simplenote/build.gradle
  Simplenote/src/main/java/com/automattic/simplenote/authentication/NewCredentialsActivity.kt
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SimplenoteAuthenticationActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/authentication/SimplenoteSignupActivity.java
  Simplenote/src/main/java/com/automattic/simplenote/utils/ThemeUtils.java
  Simplenote/src/main/res/layout/activity_signup.xml
  Simplenote/src/main/res/layout/authentication_fancy_or.xml
  Simplenote/src/main/res/layout/fragment_confirmation.xml
  Simplenote/src/main/res/layout/fragment_login.xml
  Simplenote/src/main/res/layout/fragment_magic_link_code.xml
  Simplenote/src/main/res/layout/fragment_signup.xml
  Simplenote/src/main/res/layout/new_activity_credentials.xml
  Simplenote/src/main/res/values-night/colors.xml
  Simplenote/src/main/res/values-night/styles.xml
  Simplenote/src/main/res/values-v29/arrays.xml
  Simplenote/src/main/res/values/arrays.xml
  Simplenote/src/main/res/values/colors.xml
  Simplenote/src/main/res/xml/preferences.xml
Labels: [Type] Debt, dependencies

#1749 [Tooling] Fix Ruby issues and update gems + toolkit
  .buildkite/shared-pipeline-vars
  .bundle/config
  Gemfile
  Gemfile.lock
Labels: tooling

#1754 2.36 - update release notes
  fastlane/metadata/android/en-US/changelogs/default.txt
Labels: Releases

#1756 Allow admin push on release/ branch
  fastlane/lanes/release.rb
Labels: tooling
